"""
Report Generator v3 — Comprehensive Calculation Sheet
25-30 page detailed calculation report with IS code references.

Supports: Anchored Wall, Cantilever Wall, Staged Excavation
"""

import io
import math
from datetime import date
from docx import Document
from docx.shared import Inches, Pt, Cm, RGBColor, Emu
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.table import WD_TABLE_ALIGNMENT
from docx.oxml.ns import qn
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import numpy as np


# ═══════════════════════════════════════════════════════════════
# STYLING
# ═══════════════════════════════════════════════════════════════
NAVY = RGBColor(0x1A, 0x35, 0x50)
DARK = RGBColor(0x2C, 0x3E, 0x50)
GRAY = RGBColor(0x7F, 0x8C, 0x8D)
WHITE = RGBColor(0xFF, 0xFF, 0xFF)
ACCENT = RGBColor(0x2E, 0x86, 0xC1)
RED = RGBColor(0xC0, 0x39, 0x2B)
GREEN = RGBColor(0x27, 0xAE, 0x60)
FONT = 'Arial'


def _shading(cell, hex_color):
    el = cell._element.get_or_add_tcPr()
    el.append(el.makeelement(qn('w:shd'), {qn('w:fill'): hex_color, qn('w:val'): 'clear'}))


def _table(doc, headers, rows, col_widths=None, font_size=9):
    t = doc.add_table(rows=1 + len(rows), cols=len(headers))
    t.alignment = WD_TABLE_ALIGNMENT.CENTER
    t.style = 'Table Grid'
    for i, h in enumerate(headers):
        c = t.rows[0].cells[i]
        c.text = h
        p = c.paragraphs[0]; p.alignment = WD_ALIGN_PARAGRAPH.CENTER
        r = p.runs[0]; r.bold = True; r.font.size = Pt(font_size); r.font.color.rgb = WHITE; r.font.name = FONT
        _shading(c, '1A3550')
    for ri, row in enumerate(rows):
        for ci, val in enumerate(row):
            c = t.rows[ri + 1].cells[ci]
            c.text = str(val)
            p = c.paragraphs[0]
            p.alignment = WD_ALIGN_PARAGRAPH.CENTER if ci > 0 else WD_ALIGN_PARAGRAPH.LEFT
            for r in p.runs: r.font.size = Pt(font_size); r.font.name = FONT
            if ri % 2 == 1: _shading(c, 'EBF5FB')
    if col_widths:
        for i, w in enumerate(col_widths):
            for row in t.rows: row.cells[i].width = Cm(w)
    return t


def _f(doc, text):
    """Formula line — indented, monospace."""
    p = doc.add_paragraph()
    p.paragraph_format.left_indent = Cm(1.2)
    p.paragraph_format.space_before = Pt(2)
    p.paragraph_format.space_after = Pt(2)
    r = p.add_run(text)
    r.font.name = 'Consolas'; r.font.size = Pt(9.5); r.font.color.rgb = NAVY


def _p(doc, text, bold=False, italic=False, size=10, color=DARK, after=6):
    """Paragraph."""
    p = doc.add_paragraph()
    p.paragraph_format.space_after = Pt(after)
    r = p.add_run(text)
    r.font.name = FONT; r.font.size = Pt(size); r.font.color.rgb = color
    r.bold = bold; r.italic = italic
    return p


def _ref(doc, text):
    """IS code clause reference."""
    p = doc.add_paragraph()
    p.paragraph_format.left_indent = Cm(1.2)
    p.paragraph_format.space_after = Pt(2)
    r = p.add_run(text)
    r.font.name = FONT; r.font.size = Pt(8.5); r.font.color.rgb = ACCENT; r.italic = True


def _result(doc, label, value, unit, status=None):
    p = doc.add_paragraph()
    p.paragraph_format.space_after = Pt(3)
    r = p.add_run(f"  {label}: "); r.font.name = FONT; r.font.size = Pt(10); r.bold = True
    r = p.add_run(f"{value} {unit}"); r.font.name = FONT; r.font.size = Pt(10)
    if status:
        r = p.add_run(f"  [{status}]"); r.font.name = FONT; r.font.size = Pt(10); r.bold = True
        r.font.color.rgb = GREEN if status == "PASS" else RED


def _fig(doc, fig, caption, width=6.0):
    buf = io.BytesIO()
    fig.savefig(buf, format='png', dpi=180, bbox_inches='tight', facecolor='white')
    buf.seek(0); plt.close(fig)
    p = doc.add_paragraph(); p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    p.add_run().add_picture(buf, width=Inches(width))
    c = doc.add_paragraph(caption); c.alignment = WD_ALIGN_PARAGRAPH.CENTER
    c.runs[0].font.size = Pt(8.5); c.runs[0].font.italic = True; c.runs[0].font.color.rgb = GRAY


def _init_doc():
    doc = Document()
    s = doc.styles['Normal']; s.font.name = FONT; s.font.size = Pt(10)
    for lv in [1, 2, 3]:
        h = doc.styles[f'Heading {lv}']; h.font.name = FONT; h.font.color.rgb = NAVY

    # ── Footer disclaimer on all pages ──
    section = doc.sections[0]
    footer = section.footer
    footer.is_linked_to_previous = False
    fp = footer.paragraphs[0] if footer.paragraphs else footer.add_paragraph()
    fp.alignment = WD_ALIGN_PARAGRAPH.CENTER
    fp.paragraph_format.space_before = Pt(4)
    disclaimer = ("Note: These calculations are valid under the soil conditions as stated herein. "
                  "Engineering responsibility lies with the Engineer-in-Charge. "
                  "This report is generated by Deep Excavation Analysis Tool and must be reviewed "
                  "by a qualified structural engineer before use.")
    run = fp.add_run(disclaimer)
    run.font.name = FONT
    run.font.size = Pt(8)
    run.font.color.rgb = GRAY
    run.italic = True

    return doc


# ═══════════════════════════════════════════════════════════════
# COVER PAGE
# ═══════════════════════════════════════════════════════════════
def _cover(doc, project_name, location, exc_depth, mode_title,
           firm="", engineer="", revision="R0"):
    for _ in range(5): doc.add_paragraph()
    p = doc.add_paragraph(); p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    r = p.add_run(mode_title.upper())
    r.font.size = Pt(28); r.bold = True; r.font.color.rgb = NAVY; r.font.name = FONT

    doc.add_paragraph()
    p = doc.add_paragraph(); p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    r = p.add_run("DETAILED CALCULATION REPORT")
    r.font.size = Pt(16); r.font.color.rgb = ACCENT; r.font.name = FONT

    doc.add_paragraph(); doc.add_paragraph()

    lines = [
        (project_name, 16, True), (location, 13, False),
        (f"Excavation Depth: {exc_depth:.1f} m", 12, False), ("", 10, False),
    ]
    if firm: lines.append((firm, 13, True))
    if engineer: lines.append((f"Prepared by: {engineer}", 11, False))
    lines.append((f"Date: {date.today().strftime('%d %B %Y')}", 11, False))
    lines.append((f"Revision: {revision}", 11, False))

    for text, size, bold in lines:
        p = doc.add_paragraph(); p.alignment = WD_ALIGN_PARAGRAPH.CENTER
        r = p.add_run(text); r.font.size = Pt(size); r.bold = bold
        r.font.name = FONT; r.font.color.rgb = DARK


# ═══════════════════════════════════════════════════════════════
# 1. DESIGN BASIS & CODES
# ═══════════════════════════════════════════════════════════════
def _sec_design_basis(doc, ch, exc_depth, surcharge, wall_toe, method_desc):
    doc.add_heading(f'{ch}. Design Basis', level=1)

    doc.add_heading(f'{ch}.1 Scope', level=2)
    _p(doc, f"This calculation report presents the detailed design of a sheet pile retaining wall "
       f"for a deep excavation of {exc_depth:.1f} m depth. The wall is designed to resist active "
       f"earth pressure, hydrostatic water pressure, and surcharge loading.")
    _p(doc, f"Analysis method: {method_desc}")
    _p(doc, f"Surcharge at ground level: {surcharge:.1f} kPa (uniform, permanent).")
    _p(doc, f"Wall toe level: {wall_toe:.1f} m below ground level.")

    doc.add_heading(f'{ch}.2 Design Codes and Standards', level=2)
    _table(doc,
        ["Code", "Title", "Key Clauses"],
        [
            ["IS 9527 (Part 1):1981", "Design of sheet pile walls", "Cl. 4.2 — Ka, Kp; Cl. 5 — Cantilever/Anchored"],
            ["IS 14458 (Part 1):1998", "Retaining wall design", "Cl. 5.1 — Stability; Cl. 5.3 — Pressure"],
            ["IS 800:2007", "Steel structures (LSM)", "Cl. 8.2.1 — Bending; Cl. 8.4 — Shear; Table 2"],
            ["IS 456:2000", "Reinforced concrete", "Cl. 26.2.1 — Bond; Table 4 — Dev. length"],
            ["IS 875 (Part 3):2015", "Wind loads", "Cl. 6.3 — Design wind; Cl. 7.2 — Pressure coeff."],
            ["IS 1893 (Part 1):2016", "Seismic loads", "Table 3 — Zone factors (reserved)"],
            ["FHWA-IF-99-015", "Ground anchors & anchored systems", "Ch. 4-5 — Anchor design"],
            ["BS 8081:2015", "Ground anchors", "Cl. 6.6 — Bond; Cl. 7.3 — Proof testing"],
            ["CIRIA C760", "Embedded retaining walls", "Staged construction methodology"],
        ], [4.5, 4.5, 5])

    doc.add_heading(f'{ch}.3 Partial Safety Factors', level=2)
    _ref(doc, "Ref: IS 800:2007 Table 5; IS 9527 Cl. 4.2")
    _table(doc,
        ["Factor", "Symbol", "Value", "Reference"],
        [
            ["Material safety (steel)", "gamma_m0", "1.10", "IS 800 Cl. 5.4.1"],
            ["Material safety (bolt)", "gamma_mb", "1.25", "IS 800 Cl. 5.4.1"],
            ["FOS on passive resistance", "FOS_p", "1.5 - 2.0", "IS 9527 Cl. 4.2"],
            ["FOS on anchor bond", "FOS_bond", "2.0", "FHWA Table 6"],
            ["FOS on anchor tendon", "FOS_tendon", "1.5 (temp)", "FHWA Ch. 4"],
            ["Overturning stability", "FOS_OT", ">= 1.5", "IS 14458 Cl. 5.1"],
        ], [4, 2.5, 2, 5.5])


# ═══════════════════════════════════════════════════════════════
# 2. GEOTECHNICAL PROFILE & EARTH PRESSURE
# ═══════════════════════════════════════════════════════════════
def _sec_soil(doc, ch, layers, gwt_behind, gwt_front, surcharge, exc_depth):
    doc.add_heading(f'{ch}. Geotechnical Profile & Earth Pressure Coefficients', level=1)

    doc.add_heading(f'{ch}.1 Soil Stratification', level=2)
    _ref(doc, "Ref: IS 9527 Cl. 4.2 — Earth pressure from design soil parameters")
    _p(doc, "The soil profile adopted for design is based on the geotechnical investigation report. "
       "The following table summarises the design parameters for each stratum:")

    rows = []
    for i, L in enumerate(layers):
        phi = L.get('phi', 30); c = L.get('c', 0)
        Ka = math.tan(math.radians(45 - phi/2))**2
        Kp = math.tan(math.radians(45 + phi/2))**2
        rows.append([
            L.get('name', f'Layer {i+1}'),
            f"{L.get('top',0):.1f}", f"{L.get('bottom',0):.1f}",
            f"{L.get('bottom',0) - L.get('top',0):.1f}",
            f"{L.get('gamma',18):.1f}", f"{phi:.0f}", f"{c:.0f}",
            f"{Ka:.4f}", f"{Kp:.4f}",
        ])
    _table(doc,
        ["Stratum", "Top (m)", "Bot (m)", "Thick (m)", "gamma (kN/m3)", "phi (deg)", "c' (kPa)", "Ka", "Kp"],
        rows, [2, 1.3, 1.3, 1.3, 1.8, 1.3, 1.3, 1.5, 1.5], font_size=8)

    doc.add_heading(f'{ch}.2 Groundwater Conditions', level=2)
    _table(doc,
        ["Parameter", "Value", "Remarks"],
        [
            ["GWT behind wall", f"{gwt_behind:.1f} m below GL", "Design water table (monsoon / permanent)"],
            ["GWT in front of wall", f"{gwt_front:.1f} m below GL", "Post-dewatering level"],
            ["gamma_w", "9.81 kN/m3", "Unit weight of water"],
            ["Differential head", f"{gwt_front - gwt_behind:.1f} m", "Drives net water pressure"],
        ], [4, 4, 6])

    doc.add_heading(f'{ch}.3 Earth Pressure Coefficient — Derivation', level=2)
    _ref(doc, "Ref: IS 9527 Cl. 4.2 — Rankine theory for smooth walls")
    _p(doc, "For a smooth vertical wall retaining horizontal backfill, the Rankine earth pressure "
       "coefficients are:")
    _f(doc, "Ka = tan2(45 - phi/2)     ... Active coefficient")
    _f(doc, "Kp = tan2(45 + phi/2)     ... Passive coefficient")
    _p(doc, "Derivation per stratum:")

    for L in layers:
        phi = L.get('phi', 30)
        Ka = math.tan(math.radians(45 - phi/2))**2
        Kp = math.tan(math.radians(45 + phi/2))**2
        _p(doc, f"{L.get('name', 'Layer')} (phi = {phi:.0f} deg):", bold=True)
        _f(doc, f"Ka = tan2(45 - {phi:.0f}/2) = tan2({45 - phi/2:.1f}) = {Ka:.4f}")
        _f(doc, f"Kp = tan2(45 + {phi:.0f}/2) = tan2({45 + phi/2:.1f}) = {Kp:.4f}")
        _f(doc, f"sqrt(Ka) = {math.sqrt(Ka):.4f}  (for cohesion term)")
        _f(doc, f"sqrt(Kp) = {math.sqrt(Kp):.4f}")

    doc.add_heading(f'{ch}.4 Active Earth Pressure at Key Depths', level=2)
    _ref(doc, "Ref: IS 9527 Cl. 4.2; IS 14458 Cl. 5.1.2 — Effective stress approach")
    _p(doc, "Effective horizontal active stress at depth z:")
    _f(doc, "sigma_ah'(z) = Ka x sigma_v'(z) - 2c' x sqrt(Ka)  >= 0")
    _p(doc, "Effective vertical stress:")
    _f(doc, "sigma_v'(z) = Sum(gamma_i x h_i) + q - u(z)")
    _p(doc, "Hydrostatic pore water pressure:")
    _f(doc, "u(z) = gamma_w x (z - z_wt)    for z > z_wt,  else 0")
    _p(doc, "Total active pressure (effective + water):")
    _f(doc, "p_a(z) = sigma_ah'(z) + u(z)")

    _p(doc, "Detailed computation at layer boundaries and key depths:", bold=True)

    gamma_w = 9.81
    sigma_v = surcharge  # effective vertical stress at GL
    cum = 0.0
    press_rows = [["0.00 (GL)", f"{surcharge:.2f}", "0.00", "-", "-", "0.00", "Surcharge q only"]]

    for L in layers:
        top = L.get('top', cum); bot = L.get('bottom', cum + 3)
        gamma = L.get('gamma', 18.0); phi = L.get('phi', 30); c = L.get('c', 0)
        Ka = math.tan(math.radians(45 - phi/2))**2
        thick = bot - top

        # Just below top of layer (if not at GL)
        if top > 0.01:
            _p(doc, f"At z = {top:.2f} m (top of {L.get('name','')}):")
            u_top = max(0, gamma_w * (top - gwt_behind))
            sig_ah_top = max(0, Ka * sigma_v - 2 * c * math.sqrt(Ka))
            _f(doc, f"sigma_v' = {sigma_v:.2f} kPa")
            _f(doc, f"sigma_ah' = {Ka:.4f} x {sigma_v:.2f} - 2 x {c:.0f} x {math.sqrt(Ka):.4f} = {sig_ah_top:.2f} kPa")
            _f(doc, f"u = {u_top:.2f} kPa")
            _f(doc, f"p_a = {sig_ah_top:.2f} + {u_top:.2f} = {sig_ah_top + u_top:.2f} kPa")
            press_rows.append([f"{top:.2f}", f"{sigma_v:.2f}", f"{sig_ah_top:.2f}",
                              f"{Ka:.4f}", f"{c:.0f}", f"{u_top:.2f}",
                              f"Top of {L.get('name','')}"])

        # Bottom of layer
        if bot > gwt_behind:
            above = max(0, gwt_behind - top)
            below = thick - above
            sigma_v += gamma * above + (gamma - gamma_w) * below
            u_bot = gamma_w * (bot - gwt_behind)
        else:
            sigma_v += gamma * thick
            u_bot = 0

        sig_ah_bot = max(0, Ka * sigma_v - 2 * c * math.sqrt(Ka))
        pa_bot = sig_ah_bot + u_bot

        _p(doc, f"At z = {bot:.2f} m (bottom of {L.get('name','')}):")
        _f(doc, f"sigma_v' = {sigma_v:.2f} kPa")
        _f(doc, f"sigma_ah' = {Ka:.4f} x {sigma_v:.2f} - 2 x {c:.0f} x {math.sqrt(Ka):.4f} = {sig_ah_bot:.2f} kPa")
        _f(doc, f"u = {u_bot:.2f} kPa")
        _f(doc, f"p_a = {sig_ah_bot:.2f} + {u_bot:.2f} = {pa_bot:.2f} kPa")

        press_rows.append([f"{bot:.2f}", f"{sigma_v:.2f}", f"{sig_ah_bot:.2f}",
                          f"{Ka:.4f}", f"{c:.0f}", f"{u_bot:.2f}",
                          f"Bot of {L.get('name','')}"])
        cum = bot

    # Pressure at excavation level
    _p(doc, f"At excavation level z = {exc_depth:.2f} m:", bold=True)
    _f(doc, f"Active pressure at excavation level is the critical depth for wall design.")

    _p(doc, "Summary — Active Pressure Profile:", bold=True)
    _table(doc,
        ["Depth (m)", "sigma_v' (kPa)", "sigma_ah' (kPa)", "Ka", "c' (kPa)", "u (kPa)", "Notes"],
        press_rows, [1.8, 2, 2, 1.5, 1.3, 1.5, 3.5], font_size=8)

    doc.add_heading(f'{ch}.5 Passive Earth Pressure Below Excavation', level=2)
    _ref(doc, "Ref: IS 9527 Cl. 4.2 — Passive resistance; factored by FOS")
    _p(doc, "Below excavation level, passive resistance develops in front of the wall:")
    _f(doc, "sigma_ph'(z) = Kp x sigma_v'(z) + 2c' x sqrt(Kp)")
    _p(doc, "The passive pressure is factored by FOS_passive (typically 1.5) for design:")
    _f(doc, "sigma_ph_design = sigma_ph / FOS_passive")
    _p(doc, "Net pressure below excavation:")
    _f(doc, "p_net(z) = max(0, p_active(z) - p_passive_design(z))")
    _p(doc, "The net pressure is clipped to zero — passive resistance can reduce "
       "active loading but cannot push the wall backward (physically, passive is a reaction).")


# ═══════════════════════════════════════════════════════════════
# 3. WALL CONFIGURATION & SECTION PROPERTIES
# ═══════════════════════════════════════════════════════════════
def _sec_wall_config(doc, ch, section, grade, EI, wall_toe, exc_depth):
    doc.add_heading(f'{ch}. Wall Configuration & Section Properties', level=1)

    doc.add_heading(f'{ch}.1 Wall Geometry', level=2)
    embed = wall_toe - exc_depth
    _table(doc,
        ["Parameter", "Value", "Unit"],
        [
            ["Excavation depth", f"{exc_depth:.1f}", "m"],
            ["Wall toe depth", f"{wall_toe:.1f}", "m below GL"],
            ["Embedment below excavation", f"{embed:.1f}", "m"],
            ["Total wall length", f"{wall_toe:.1f}", "m"],
            ["Embedment ratio", f"{embed/exc_depth:.2f}", "D/H"],
        ], [5, 3, 3])

    doc.add_heading(f'{ch}.2 Sheet Pile Section Properties', level=2)
    _ref(doc, "Ref: IS 800:2007 Table 2 — Section classification; Manufacturer catalogue")
    if section:
        fy = 355 if '355' in grade else (240 if '240' in grade else 355)
        _table(doc,
            ["Property", "Symbol", "Value", "Unit"],
            [
                ["Section designation", "-", section.name, "-"],
                ["Profile type", "-", section.profile_type.value if hasattr(section.profile_type, 'value') else str(section.profile_type), "-"],
                ["Manufacturer", "-", section.manufacturer, "-"],
                ["System width", "b", f"{section.width:.0f}", "mm"],
                ["Overall depth", "h", f"{section.height:.0f}", "mm"],
                ["Web thickness", "t_w", f"{section.thickness_web:.1f}", "mm"],
                ["Flange thickness", "t_f", f"{section.thickness_flange:.1f}", "mm"],
                ["Cross-sectional area", "A", f"{section.area:.1f}", "cm2/m"],
                ["Moment of inertia", "I", f"{section.moment_of_inertia:.0f}", "cm4/m"],
                ["Elastic section modulus", "Z_e", f"{section.elastic_modulus:.0f}", "cm3/m"],
                ["Plastic section modulus", "Z_p", f"{section.plastic_modulus:.0f}", "cm3/m"],
                ["Weight", "w", f"{section.weight:.1f}", "kg/m2"],
                ["Steel grade", "-", grade, "-"],
                ["Yield strength", "f_y", f"{fy}", "MPa"],
                ["Elastic modulus (steel)", "E", "210000", "MPa"],
                ["Flexural rigidity", "EI", f"{EI:.0f}", "kN.m2/m"],
            ], [4, 2, 3, 2.5])

        shape_factor = section.plastic_modulus / section.elastic_modulus if section.elastic_modulus > 0 else 1.0
        _p(doc, f"Shape factor Z_p/Z_e = {section.plastic_modulus:.0f}/{section.elastic_modulus:.0f} = {shape_factor:.3f}")
        if shape_factor >= 1.15:
            _p(doc, f"Section class: 1 (Plastic) — shape factor >= 1.15")
        elif shape_factor >= 1.0:
            _p(doc, f"Section class: 2 (Compact) — shape factor >= 1.0")
        else:
            _p(doc, f"Section class: 3 (Semi-compact)")

    doc.add_heading(f'{ch}.3 Flexural Rigidity Calculation', level=2)
    _ref(doc, "Ref: IS 800:2007 Cl. 4.1 — Material properties")
    _f(doc, "EI = E x I")
    if section:
        _f(doc, f"EI = 210000 MPa x {section.moment_of_inertia:.0f} cm4/m")
        _f(doc, f"EI = 210000 x {section.moment_of_inertia:.0f} x 10^-8  (cm4 to m4)")
        _f(doc, f"EI = {EI:.0f} kN.m2/m")


# ═══════════════════════════════════════════════════════════════
# 4. ANALYSIS METHOD & FE MODEL
# ═══════════════════════════════════════════════════════════════
def _sec_fe_model(doc, ch, wall_toe, n_anchors, anchor_levels, exc_depth):
    doc.add_heading(f'{ch}. Analysis Method & Finite Element Model', level=1)

    doc.add_heading(f'{ch}.1 Beam-on-Elastic-Foundation Model', level=2)
    _p(doc, "The wall is modelled as a one-dimensional Euler-Bernoulli beam discretised into "
       "finite elements along its length. The soil loading is applied as a distributed pressure "
       "converted to equivalent nodal forces using consistent load vectors.")

    _p(doc, "Key assumptions:", bold=True)
    _p(doc, "1. Plane strain conditions — wall analysed per metre of wall run.")
    _p(doc, "2. Linear-elastic beam elements with constant EI.")
    _p(doc, "3. Small displacement theory (geometric linearity).")
    _p(doc, "4. Rankine earth pressure (smooth wall, horizontal backfill).")
    _p(doc, "5. Active pressure applied as loading; passive pressure as factored resistance below excavation.")

    doc.add_heading(f'{ch}.2 Element Discretisation', level=2)
    n_elem = int(wall_toe / 0.1)
    n_nodes = n_elem + 1
    _p(doc, f"Wall length: {wall_toe:.1f} m, element size: 0.1 m")
    _f(doc, f"Number of elements: {n_elem}")
    _f(doc, f"Number of nodes: {n_nodes}")
    _f(doc, f"DOF per node: 2 (lateral displacement w, rotation theta)")
    _f(doc, f"Total DOF: {n_nodes * 2}")

    doc.add_heading(f'{ch}.3 Boundary Conditions & Supports', level=2)
    _p(doc, "Support conditions:", bold=True)
    supp_rows = []
    for i in range(n_anchors):
        lvl = anchor_levels[i] if i < len(anchor_levels) else 0
        supp_rows.append([f"Anchor {i+1}", f"{lvl:.1f} m", "Pin (w = 0)", "Horizontal reaction"])
    supp_rows.append(["Toe", f"{wall_toe:.1f} m", "Fixed (w = 0, theta = 0)", "Reaction + moment"])
    supp_rows.append(["Wall top", "0.0 m", "Free", "No restraint"])
    _table(doc,
        ["Support", "Depth", "Condition", "Provides"],
        supp_rows, [2.5, 2.5, 4, 5])

    doc.add_heading(f'{ch}.4 Stiffness Matrix', level=2)
    _ref(doc, "Standard Euler-Bernoulli beam element stiffness (Przemieniecki)")
    _p(doc, "Element stiffness matrix (4x4) for element of length L_e:")
    _f(doc, "k_e = (EI / L_e^3) x [12   6Le  -12  6Le ]")
    _f(doc, "                       [6Le  4Le2 -6Le 2Le2]")
    _f(doc, "                       [-12 -6Le   12 -6Le ]")
    _f(doc, "                       [6Le  2Le2 -6Le 4Le2]")
    _p(doc, "Global stiffness assembled by direct stiffness method. "
       "Boundary conditions applied by zeroing rows/columns and setting diagonal to 1.")


# ═══════════════════════════════════════════════════════════════
# 5. INTERNAL FORCES — DETAILED TABULATION
# ═══════════════════════════════════════════════════════════════
def _sec_internal_forces(doc, ch, result, exc_depth, label=""):
    doc.add_heading(f'{ch}. Internal Forces — {label}', level=1)

    doc.add_heading(f'{ch}.1 Bending Moment Distribution', level=2)
    _ref(doc, "Ref: IS 9527 Cl. 5 — BM from equilibrium of pressures and reactions")
    _p(doc, "Bending moments computed from the beam FE solution at each node. "
       "Positive BM indicates tension on the excavation face.")

    # Sample at 0.5m intervals for tabulation
    depths = list(result.depths) if hasattr(result, 'depths') and result.depths is not None else []
    bm = list(result.bending_moments) if hasattr(result, 'bending_moments') and result.bending_moments is not None else []
    sf = list(result.shear_forces) if hasattr(result, 'shear_forces') and result.shear_forces is not None else []
    defl = list(result.deflections) if hasattr(result, 'deflections') and result.deflections is not None else []

    if len(depths) > 0:
        step = max(1, len(depths) // 40)  # ~40 rows max
        bm_rows = []
        for i in range(0, len(depths), step):
            d = depths[i]
            m = bm[i] if i < len(bm) else 0
            s = sf[i] if i < len(sf) else 0
            dl = defl[i] if i < len(defl) else 0
            zone = "Above exc." if d < exc_depth else "Embedment"
            bm_rows.append([f"{d:.2f}", f"{m:.2f}", f"{s:.2f}", f"{dl:.2f}", zone])
        # Always include last node
        if len(depths) > 1:
            i = len(depths) - 1
            bm_rows.append([f"{depths[i]:.2f}",
                           f"{bm[i] if i < len(bm) else 0:.2f}",
                           f"{sf[i] if i < len(sf) else 0:.2f}",
                           f"{defl[i] if i < len(defl) else 0:.2f}",
                           "Toe"])

        _table(doc,
            ["Depth (m)", "BM (kN.m/m)", "SF (kN/m)", "Defl (mm)", "Zone"],
            bm_rows, [2, 2.5, 2.5, 2.5, 3], font_size=8)

    doc.add_heading(f'{ch}.2 Peak Values', level=2)
    max_bm = max(abs(m) for m in bm) if bm is not None and len(bm) > 0 else 0
    max_sf = max(abs(s) for s in sf) if sf is not None and len(sf) > 0 else 0
    max_defl = max(abs(d) for d in defl) if defl is not None and len(defl) > 0 else 0
    bm_depth = depths[max(range(len(bm)), key=lambda i: abs(bm[i]))] if bm else 0
    sf_depth = depths[max(range(len(sf)), key=lambda i: abs(sf[i]))] if sf else 0
    defl_depth = depths[max(range(len(defl)), key=lambda i: abs(defl[i]))] if defl else 0

    _result(doc, "Maximum Bending Moment", f"{max_bm:.2f}", f"kN.m/m at {bm_depth:.2f} m depth")
    _result(doc, "Maximum Shear Force", f"{max_sf:.2f}", f"kN/m at {sf_depth:.2f} m depth")
    _result(doc, "Maximum Deflection", f"{max_defl:.2f}", f"mm at {defl_depth:.2f} m depth")

    doc.add_heading(f'{ch}.3 Deflection Assessment', level=2)
    _ref(doc, "Ref: CIRIA C760 Table 4.1 — Serviceability limits for retaining walls")
    _p(doc, "Serviceability check — maximum allowable deflection:")
    _f(doc, f"delta_max = H / 200  (typical for temporary works)")
    _f(doc, f"delta_allow = {exc_depth * 1000 / 200:.1f} mm")
    _f(doc, f"delta_actual = {max_defl:.1f} mm")
    ratio = max_defl / (exc_depth * 1000 / 200) if exc_depth > 0 else 0
    _f(doc, f"Utilization = {max_defl:.1f} / {exc_depth * 1000 / 200:.1f} = {ratio:.3f} ({ratio*100:.1f}%)")
    status = "PASS" if ratio <= 1.0 else "FAIL"
    _result(doc, "Deflection serviceability", f"{ratio*100:.1f}%", "utilization", status)


# ═══════════════════════════════════════════════════════════════
# COMBINED CROSS-SECTION FIGURE (for report)
# ═══════════════════════════════════════════════════════════════
def _sec_combined_figure(doc, ch, layers, gwt_behind, gwt_front, exc_depth, wall_toe,
                         anchors_ui, result, surcharge, section_name, Md=0, fos_passive=1.5):
    doc.add_heading(f'{ch}. Combined Analysis Overview', level=1)
    _p(doc, "The following figure presents a combined view of the lateral pressure distribution, "
       "wall cross-section with support reactions, bending moment diagram with section capacity, "
       "and deflected shape.")

    gamma_w = 9.81
    max_depth = max(wall_toe + 1, max(L['bottom'] for L in layers))

    fig, (ax1, ax2, ax3, ax4) = plt.subplots(1, 4, figsize=(18, 10),
        gridspec_kw={'width_ratios': [2.5, 1.5, 2, 1.5], 'wspace': 0.12})

    # ── Panel 1: Pressure ──
    dz = 0.1
    z_arr, pa_t, pp_t = [], [], []
    z = 0.0
    while z <= wall_toe + 0.05:
        phi, c, gamma = 30, 0, 18
        for L in layers:
            if L['top'] <= z < L['bottom']:
                phi = L.get('phi', 30); c = L.get('c', 0); gamma = L.get('gamma', 18)
                break
        Ka = math.tan(math.radians(45 - phi/2))**2
        sv = surcharge
        cum = 0
        for L in layers:
            lt, lb = L['top'], L['bottom']
            g = L.get('gamma', 18)
            if z <= lt: break
            z_in = min(z, lb) - lt
            if lb > gwt_behind:
                above = max(0, min(z_in, gwt_behind - lt))
                below = z_in - above
                sv += g * above + (g - gamma_w) * below
            else:
                sv += g * z_in
            cum = lb
        sig_ah = max(0, Ka * sv - 2 * c * math.sqrt(Ka))
        u_b = max(0, gamma_w * (z - gwt_behind))
        act = sig_ah + u_b
        pas = 0.0
        if z > exc_depth:
            sv_f = 0
            Kp = math.tan(math.radians(45 + phi/2))**2
            for L in layers:
                lt, lb = L['top'], L['bottom']
                if lb <= exc_depth: continue
                zs = max(exc_depth, lt); ze = min(z, lb)
                if ze <= zs: continue
                sv_f += L.get('gamma', 18) * (ze - zs)
            u_f = max(0, gamma_w * (z - gwt_front))
            pas = (Kp * sv_f + 2 * c * math.sqrt(Kp) + u_f) / fos_passive

        z_arr.append(z); pa_t.append(act); pp_t.append(pas)
        z += dz

    ax1.fill_betweenx(z_arr, 0, pa_t, alpha=0.2, color='#E74C3C')
    ax1.plot(pa_t, z_arr, '#C0392B', lw=2, label='Active')
    ax1.fill_betweenx(z_arr, 0, [-p for p in pp_t], alpha=0.15, color='#27AE60')
    ax1.plot([-p for p in pp_t], z_arr, '#27AE60', lw=2, label='Passive/FOS')
    ax1.axvline(0, color='black', lw=0.5)
    ax1.axhline(exc_depth, color='#C0392B', ls='--', lw=1.5)
    ax1.set_xlabel('Pressure (kPa)', fontsize=11, fontweight='bold')
    ax1.set_ylabel('Depth (m)', fontsize=11, fontweight='bold')
    ax1.set_title('Lateral Pressure', fontweight='bold', fontsize=13)
    ax1.invert_yaxis(); ax1.set_ylim(max_depth, 0)
    ax1.legend(fontsize=9); ax1.grid(True, alpha=0.15)

    # ── Panel 2: Cross-section ──
    soil_colors = ['#D4A574', '#C4956A', '#A0886C', '#8B9467', '#7D8B6A', '#6B7D5E']
    for i, L in enumerate(layers):
        color = soil_colors[i % len(soil_colors)]
        if 'rock' in L['name'].lower(): color = '#8B8B6E'
        ax2.fill_between([-1, 0], L['top'], L['bottom'], color=color, alpha=0.7)
        if L['bottom'] <= exc_depth:
            ax2.fill_between([0, 1], L['top'], L['bottom'], color='white')
        elif L['top'] < exc_depth:
            ax2.fill_between([0, 1], L['top'], exc_depth, color='white')
            ax2.fill_between([0, 1], exc_depth, L['bottom'], color=color, alpha=0.7)
        else:
            ax2.fill_between([0, 1], L['top'], L['bottom'], color=color, alpha=0.7)
        mid = (L['top'] + min(L['bottom'], max_depth)) / 2
        ax2.text(-0.5, mid, L['name'], fontsize=8, ha='center', va='center',
                fontweight='bold', color='white',
                bbox=dict(boxstyle='round,pad=0.2', facecolor='#2C3E50', alpha=0.85))

    ax2.fill_between([-0.04, 0.04], 0, wall_toe, color='#2C3E50')
    ax2.axhline(gwt_behind, color='#2E86C1', ls='--', lw=2, alpha=0.8)
    ax2.axhline(exc_depth, color='#C0392B', ls='--', lw=2)
    ax2.text(0.5, exc_depth, f'Exc.{exc_depth}m', fontsize=8, color='#C0392B',
            fontweight='bold', va='bottom', ha='center',
            bbox=dict(boxstyle='round', facecolor='white', edgecolor='#C0392B'))

    for i, a in enumerate(anchors_ui):
        lvl = a['level'] if isinstance(a, dict) else a.level
        incl = a.get('incl', 20) if isinstance(a, dict) else getattr(a, 'inclination', 20)
        spc = a.get('spacing', 3.0) if isinstance(a, dict) else getattr(a, 'horizontal_spacing', 3.0)
        rxn = abs(result.anchor_reactions[i]) if i < len(result.anchor_reactions) else 0
        dx = 0.7 * math.cos(math.radians(incl))
        dy = 0.7 * math.sin(math.radians(incl))
        ax2.annotate('', xy=(-dx, lvl + dy), xytext=(0, lvl),
                    arrowprops=dict(arrowstyle='->', color='#C0392B', lw=2.5))
        ax2.text(-dx - 0.1, lvl + dy, f'A{i+1}:{rxn*spc:.0f}kN',
                fontsize=7, fontweight='bold', color='#C0392B', ha='right',
                bbox=dict(boxstyle='round,pad=0.2', facecolor='#FADBD8', edgecolor='#C0392B'))

    ax2.set_xlim(-1.2, 1.2); ax2.set_ylim(max_depth, 0)
    ax2.set_title('Cross-Section', fontweight='bold', fontsize=13)
    ax2.set_xticks([]); ax2.grid(True, alpha=0.1, axis='y')

    # ── Panel 3: BM ──
    depths = list(result.depths) if hasattr(result, 'depths') and result.depths is not None else []
    bm = list(result.bending_moments) if hasattr(result, 'bending_moments') and result.bending_moments is not None else []
    if depths is not None and len(depths) > 0 and bm is not None and len(bm) > 0:
        ax3.plot(bm, depths, '#1A5276', lw=2.5)
        ax3.fill_betweenx(depths, 0, bm, alpha=0.1, color='#1A5276')
        if Md > 0:
            ax3.axvline(Md, color='#C0392B', ls='-.', lw=1.5, label=f'Md={Md:.0f}')
            ax3.axvline(-Md, color='#C0392B', ls='-.', lw=1.5)
        ax3.axvline(0, color='black', lw=0.5)
        ax3.axhline(exc_depth, color='#C0392B', ls='--', lw=1.5)
        max_idx = max(range(len(bm)), key=lambda i: abs(bm[i]))
        ax3.annotate(f'{bm[max_idx]:.1f}\nat {depths[max_idx]:.1f}m',
                    xy=(bm[max_idx], depths[max_idx]), xytext=(bm[max_idx]-20, depths[max_idx]-0.8),
                    fontsize=9, fontweight='bold', color='#1A5276',
                    arrowprops=dict(arrowstyle='->', color='#1A5276'),
                    bbox=dict(boxstyle='round', facecolor='#D6EAF8', edgecolor='#1A5276'))
    ax3.set_xlabel('BM (kN.m/m)', fontsize=11, fontweight='bold')
    ax3.set_title('Bending Moment', fontweight='bold', fontsize=13)
    ax3.invert_yaxis(); ax3.set_ylim(max_depth, 0)
    if Md > 0: ax3.legend(fontsize=9)
    ax3.grid(True, alpha=0.15)

    # ── Panel 4: Deflection ──
    defl = list(result.deflections) if hasattr(result, 'deflections') and result.deflections is not None else []
    if depths is not None and len(depths) > 0 and defl is not None and len(defl) > 0:
        ax4.plot(defl, depths, '#6C3483', lw=2.5)
        ax4.fill_betweenx(depths, 0, defl, alpha=0.1, color='#6C3483')
        d_limit = exc_depth * 1000 / 200
        ax4.axvline(d_limit, color='#E67E22', ls='-.', lw=1.5, label=f'H/200={d_limit:.0f}mm')
        ax4.axvline(0, color='black', lw=0.5, ls='--')
        ax4.axhline(exc_depth, color='#C0392B', ls='--', lw=1.5)
    ax4.set_xlabel('Deflection (mm)', fontsize=11, fontweight='bold')
    ax4.set_title('Deflected Shape', fontweight='bold', fontsize=13)
    ax4.invert_yaxis(); ax4.set_ylim(max_depth, 0)
    ax4.legend(fontsize=9); ax4.grid(True, alpha=0.15)

    fig.suptitle(f'Combined Analysis — {section_name}', fontweight='bold', fontsize=14, y=0.99)
    try:
        fig.tight_layout(rect=[0, 0, 1, 0.96])
    except Exception:
        pass
    _fig(doc, fig, "Figure: Combined Cross-Section — Pressure, Wall, BM & Deflection", 7.0)


# ═══════════════════════════════════════════════════════════════
# 6. BM/SF/DEFLECTION DIAGRAMS
# ═══════════════════════════════════════════════════════════════
def _sec_diagrams(doc, ch, result, result_wind, anchors_ui, exc_depth, prefix=""):
    doc.add_heading(f'{ch}. {prefix}Internal Force Diagrams', level=1)

    depths = list(result.depths) if hasattr(result, 'depths') and result.depths is not None else []
    bm = list(result.bending_moments) if hasattr(result, 'bending_moments') and result.bending_moments is not None else []
    sf = list(result.shear_forces) if hasattr(result, 'shear_forces') and result.shear_forces is not None else []
    defl = list(result.deflections) if hasattr(result, 'deflections') and result.deflections is not None else []

    if not depths:
        _p(doc, "No analysis data available for plotting.")
        return

    fig, (ax1, ax2, ax3) = plt.subplots(1, 3, figsize=(14, 8), sharey=True)

    ax1.plot(bm, depths, '#1A5276', lw=2, label='Earth only')
    ax1.fill_betweenx(depths, 0, bm, alpha=0.12, color='#1A5276')
    if result_wind:
        bm_w = result_wind.bending_moments
        ax1.plot(bm_w, result_wind.depths, '#C0392B', lw=2, label='Earth+Wind')
        ax1.fill_betweenx(result_wind.depths, 0, bm_w, alpha=0.12, color='#C0392B')
    ax1.axhline(exc_depth, color='#C0392B', ls='--', lw=1)
    ax1.axvline(0, color='black', lw=0.5)
    for a in (anchors_ui or []):
        lvl = a['level'] if isinstance(a, dict) else getattr(a, 'level', 0)
        ax1.axhline(lvl, color='#B22222', ls=':', lw=0.8)
    ax1.set_xlabel('BM (kN.m/m)', fontsize=12); ax1.set_ylabel('Depth (m)', fontsize=12)
    ax1.set_title('Bending Moment', fontweight='bold', fontsize=14)
    ax1.invert_yaxis(); ax1.legend(fontsize=10); ax1.grid(True, alpha=0.2)

    ax2.plot(sf, depths, '#1A5276', lw=2)
    if result_wind:
        ax2.plot(result_wind.shear_forces, result_wind.depths, '#C0392B', lw=2)
    ax2.axhline(exc_depth, color='#C0392B', ls='--', lw=1)
    ax2.axvline(0, color='black', lw=0.5)
    ax2.set_xlabel('SF (kN/m)', fontsize=12)
    ax2.set_title('Shear Force', fontweight='bold', fontsize=14)
    ax2.grid(True, alpha=0.2)

    ax3.plot(defl, depths, '#6C3483', lw=2.5)
    ax3.axhline(exc_depth, color='#C0392B', ls='--', lw=1)
    ax3.axvline(0, color='black', lw=0.5, ls='--')
    ax3.set_xlabel('Deflection (mm)', fontsize=12)
    ax3.set_title('Deflected Shape', fontweight='bold', fontsize=14)
    ax3.grid(True, alpha=0.2)

    fig.suptitle(f'{prefix}BM, SF & Deflection', fontweight='bold', y=0.99, fontsize=15)
    try:
        fig.tight_layout(rect=[0, 0, 1, 0.96])
    except Exception:
        pass
    _fig(doc, fig, f"Figure: {prefix}Bending Moment, Shear Force and Deflection Diagrams", 6.5)


# ═══════════════════════════════════════════════════════════════
# 7. ANCHOR REACTIONS & EQUILIBRIUM
# ═══════════════════════════════════════════════════════════════
def _sec_reactions(doc, ch, result, anchors_ui, wall_toe):
    doc.add_heading(f'{ch}. Support Reactions & Global Equilibrium', level=1)
    _ref(doc, "Ref: IS 9527 Cl. 5.3 — Equilibrium of anchored walls")

    _p(doc, "The support reactions are obtained from the beam FE solution. "
       "The sum of all reactions must equal the total applied load for equilibrium.")

    rows = []; total = 0
    for i, rxn in enumerate(result.anchor_reactions):
        lvl = anchors_ui[i]['level'] if isinstance(anchors_ui[i], dict) else anchors_ui[i].level
        spc = anchors_ui[i].get('spacing', 3.0) if isinstance(anchors_ui[i], dict) else getattr(anchors_ui[i], 'horizontal_spacing', 3.0)
        rows.append([f"Anchor {i+1}", f"{lvl:.1f}", f"{abs(rxn):.2f}", f"{spc:.1f}", f"{abs(rxn)*spc:.2f}"])
        total += abs(rxn)
    rows.append(["Toe", f"{wall_toe:.1f}", f"{abs(result.toe_reaction):.2f}", "-", "-"])
    total += abs(result.toe_reaction)
    rows.append(["TOTAL", "-", f"{total:.2f}", "-", "-"])

    _table(doc,
        ["Support", "Depth (m)", "Reaction (kN/m)", "Spacing (m)", "Force/Anchor (kN)"],
        rows, [2.5, 2, 3, 2, 3])

    _p(doc, "Equilibrium check:", bold=True)
    _f(doc, f"Sum of reactions = {total:.2f} kN/m")
    _p(doc, "This must equal the net integrated loading on the beam (within numerical tolerance).")


# ═══════════════════════════════════════════════════════════════
# 8. ANCHOR DESIGN — DETAILED
# ═══════════════════════════════════════════════════════════════
def _sec_anchor_design(doc, ch, anchors_ui, anchor_designs, anchor_reactions, exc_depth):
    doc.add_heading(f'{ch}. Anchor Design — Detailed Calculations', level=1)
    _ref(doc, "Ref: IS 9527 Cl. 4.2; FHWA-IF-99-015 Ch. 4; BS 8081:2015 Cl. 6.6")

    _p(doc, "Design procedure for each anchor tier:", bold=True)
    _p(doc, "Step 1: Compute design force from wall analysis reaction.")
    _f(doc, "F_design = R_horizontal x spacing / cos(alpha)")
    _p(doc, "Step 2: Select tendon and check tensile capacity.")
    _f(doc, "F_capacity >= F_design x FOS_tendon")
    _p(doc, "Step 3: Compute required bond length.")
    _f(doc, "L_bond = F_design x FOS_bond / (pi x d_hole x tau_bond)")
    _p(doc, "Step 4: Determine free length (FHWA minimum 3.0 m or beyond failure plane).")
    _f(doc, "L_free >= max(0.15H + d_anchor_level, 3.0 m)")
    _p(doc, "Step 5: Total anchor length = free length + bond length.")

    for i, ad in enumerate(anchor_designs):
        anc = anchors_ui[i]
        level = anc['level'] if isinstance(anc, dict) else anc.level
        incl = anc.get('incl', 20) if isinstance(anc, dict) else getattr(anc, 'inclination', 20)
        spc = anc.get('spacing', 3.0) if isinstance(anc, dict) else getattr(anc, 'horizontal_spacing', 3.0)
        tau = anc.get('bond_stress', 200) if isinstance(anc, dict) else getattr(anc, 'bond_stress', 200)
        d_hole = anc.get('drill_dia', 115) if isinstance(anc, dict) else getattr(anc, 'drill_diameter', 0.115)
        if d_hole > 1: d_hole = d_hole / 1000
        a_type = anc.get('type', 'rebar') if isinstance(anc, dict) else getattr(anc, 'anchor_type', 'rebar')

        doc.add_heading(f'{ch}.{i+1} Anchor {i+1} at {level:.1f} m — {a_type.upper()}', level=2)

        r_horiz = abs(anchor_reactions[i])
        r_per = r_horiz * spc
        bar_f = r_per / math.cos(math.radians(incl))

        _p(doc, "Step 1 — Design anchor force:", bold=True)
        _f(doc, f"R_horizontal = {r_horiz:.2f} kN/m  (from beam FE)")
        _f(doc, f"Spacing = {spc:.1f} m c/c")
        _f(doc, f"Force per anchor = {r_horiz:.2f} x {spc:.1f} = {r_per:.2f} kN")
        _f(doc, f"Inclination alpha = {incl:.0f} deg")
        _f(doc, f"Force along anchor axis = {r_per:.2f} / cos({incl:.0f}) = {bar_f:.2f} kN")

        _p(doc, "Step 2 — Tendon capacity:", bold=True)
        _ref(doc, f"Type: {a_type.upper()}")
        _f(doc, f"Tendon capacity = {ad.tendon_force:.1f} kN")
        _f(doc, f"FOS_tendon = {ad.tendon_force:.1f} / {bar_f:.1f} = {ad.fos_tendon_actual:.2f}")
        status_t = "PASS" if ad.fos_tendon_actual >= 1.15 else "FAIL"
        _result(doc, "Tendon check", f"FOS = {ad.fos_tendon_actual:.2f}", f"(>= 1.15 req'd)", status_t)

        _p(doc, "Step 3 — Bond length:", bold=True)
        _ref(doc, f"Ref: IS 456 Cl. 26.2.1; d_hole = {d_hole*1000:.0f} mm, tau = {tau:.0f} kPa")
        bond_cap = math.pi * d_hole * tau
        fos_b = 2.0
        Lb = bar_f * fos_b / bond_cap
        _f(doc, f"Bond capacity per m = pi x {d_hole*1000:.0f}/1000 x {tau:.0f} = {bond_cap:.2f} kN/m")
        _f(doc, f"L_bond = {bar_f:.2f} x {fos_b:.1f} / {bond_cap:.2f} = {Lb:.2f} m")
        _result(doc, "Bond FOS", f"{ad.fos_bond_actual:.2f}", f"(>= 2.0 req'd)",
                "PASS" if ad.fos_bond_actual >= 2.0 else "FAIL")

        _p(doc, "Step 4 & 5 — Free length and total:", bold=True)
        _f(doc, f"Free length (minimum) = max(0.15 x {exc_depth:.0f} + {level:.1f}, 3.0) = {max(0.15*exc_depth+level, 3.0):.1f} m")
        _f(doc, f"Total anchor length = {ad.total_length:.1f} m")

        _p(doc, "Summary:", bold=True)
        _table(doc,
            ["Check", "Required", "Provided", "FOS", "Status"],
            [
                ["Tendon", f"{bar_f:.1f} kN", f"{ad.tendon_force:.1f} kN", f"{ad.fos_tendon_actual:.2f}", "OK" if ad.fos_tendon_actual >= 1.15 else "CHECK"],
                ["Bond", f"{Lb:.2f} m", f"{ad.bond_length_required:.2f} m", f"{ad.fos_bond_actual:.2f}", "OK" if ad.fos_bond_actual >= 2.0 else "CHECK"],
                ["Total length", "-", f"{ad.total_length:.1f} m", "-", "-"],
                ["Recommendation", "-", ad.tendon_recommendation, "-", ad.status],
            ], [2.5, 2.5, 3, 2, 2.5])


# ═══════════════════════════════════════════════════════════════
# 9. SECTION CAPACITY CHECK — IS 800:2007
# ═══════════════════════════════════════════════════════════════
def _sec_capacity(doc, ch, section, grade, design_bm, design_sf, EI):
    doc.add_heading(f'{ch}. Section Adequacy — IS 800:2007', level=1)
    if not section:
        _p(doc, "Section object not available for capacity check.")
        return

    fy = 355 if '355' in grade else (240 if '240' in grade else 355)
    gm0 = 1.10

    doc.add_heading(f'{ch}.1 Bending Capacity (Cl. 8.2.1.2)', level=2)
    _ref(doc, "Ref: IS 800:2007 Cl. 8.2.1.2 — Design bending strength")
    _p(doc, "For a laterally supported beam (sheet pile wall embedded in soil):")
    _f(doc, "M_d = beta_b x Z_p x f_y / gamma_m0")
    _p(doc, "where beta_b = 1.0 for Class 1 and 2 sections (plastic/compact).")
    _f(doc, f"M_d = 1.0 x {section.plastic_modulus:.0f} x {fy} / {gm0}")
    _f(doc, f"M_d = {section.plastic_modulus:.0f} x {fy} / ({gm0} x 10^3)  [cm3 to m, MPa to kN]")
    Md = fy * section.plastic_modulus * 1e-3 / gm0
    _f(doc, f"M_d = {Md:.2f} kN.m/m")
    _p(doc, "")
    _f(doc, f"Design BM = {abs(design_bm):.2f} kN.m/m")
    util_bm = abs(design_bm) / Md if Md > 0 else 999
    _f(doc, f"Utilization = {abs(design_bm):.2f} / {Md:.2f} = {util_bm:.4f} ({util_bm*100:.1f}%)")
    _result(doc, "BENDING CHECK", f"{util_bm*100:.1f}%", "utilization", "PASS" if util_bm <= 1.0 else "FAIL")

    # Also check elastic moment capacity
    _p(doc, "Elastic moment capacity (for comparison):")
    Me = fy * section.elastic_modulus * 1e-3 / gm0
    _f(doc, f"M_e = f_y x Z_e / gamma_m0 = {fy} x {section.elastic_modulus:.0f} / ({gm0} x 10^3) = {Me:.2f} kN.m/m")

    doc.add_heading(f'{ch}.2 Shear Capacity (Cl. 8.4.1)', level=2)
    _ref(doc, "Ref: IS 800:2007 Cl. 8.4.1 — Design shear strength")
    _f(doc, "V_d = A_v x f_yw / (sqrt(3) x gamma_m0)")
    _p(doc, "For Z-profile and U-profile sheet piles, the shear area is approximately:")
    _f(doc, "A_v = h x t_w  (per m of wall)")
    Av_mm2 = section.height * section.thickness_web  # mm2 per pile, approx
    Av_cm2 = Av_mm2 / 100  # to cm2
    _f(doc, f"A_v = {section.height:.0f} x {section.thickness_web:.1f} = {Av_mm2:.0f} mm2")
    Vd = fy * Av_mm2 / (math.sqrt(3) * gm0 * 1000)  # kN
    _f(doc, f"V_d = {Av_mm2:.0f} x {fy} / (1.732 x {gm0} x 1000)")
    _f(doc, f"V_d = {Vd:.2f} kN/m")
    util_sf = abs(design_sf) / Vd if Vd > 0 else 999
    _f(doc, f"Design SF = {abs(design_sf):.2f} kN/m")
    _f(doc, f"Utilization = {abs(design_sf):.2f} / {Vd:.2f} = {util_sf:.4f} ({util_sf*100:.1f}%)")
    _result(doc, "SHEAR CHECK", f"{util_sf*100:.1f}%", "utilization", "PASS" if util_sf <= 1.0 else "FAIL")

    doc.add_heading(f'{ch}.3 Moment-Shear Interaction (Cl. 9.2.2)', level=2)
    _ref(doc, "Ref: IS 800:2007 Cl. 9.2.2 — If V <= 0.6 Vd, no reduction in moment capacity")
    v_ratio = abs(design_sf) / Vd if Vd > 0 else 0
    util_int = 0
    if v_ratio <= 0.6:
        _p(doc, f"V/Vd = {v_ratio:.3f} <= 0.6  =>  No reduction in moment capacity required.")
        _result(doc, "Interaction check", "Not required", "(V/Vd <= 0.6)", "PASS")
    else:
        beta_mv = (2 * v_ratio - 1)**2
        Md_red = Md * (1 - beta_mv)
        _f(doc, f"V/Vd = {v_ratio:.3f} > 0.6  =>  Reduced moment capacity:")
        _f(doc, f"beta = (2V/Vd - 1)^2 = {beta_mv:.4f}")
        _f(doc, f"Md_reduced = {Md:.2f} x (1 - {beta_mv:.4f}) = {Md_red:.2f} kN.m/m")
        util_int = abs(design_bm) / Md_red if Md_red > 0 else 999
        _f(doc, f"Utilization = {abs(design_bm):.2f} / {Md_red:.2f} = {util_int:.4f} ({util_int*100:.1f}%)")
        _result(doc, "Interaction check", f"{util_int*100:.1f}%", "utilization",
                "PASS" if util_int <= 1.0 else "FAIL")

    doc.add_heading(f'{ch}.4 Overall Section Adequacy', level=2)
    overall = max(util_bm, util_sf, util_int)
    _p(doc, "Summary of section checks:", bold=True)
    int_status = "PASS" if util_int <= 1.0 else "FAIL"
    int_label = f"{util_int*100:.1f}%" if util_int > 0 else "N/A"
    _table(doc,
        ["Check", "Demand", "Capacity", "Utilization", "Status"],
        [
            ["Bending (Cl. 8.2.1)", f"{abs(design_bm):.1f} kN.m/m", f"{Md:.1f} kN.m/m",
             f"{util_bm*100:.1f}%", "PASS" if util_bm <= 1.0 else "FAIL"],
            ["Shear (Cl. 8.4.1)", f"{abs(design_sf):.1f} kN/m", f"{Vd:.1f} kN/m",
             f"{util_sf*100:.1f}%", "PASS" if util_sf <= 1.0 else "FAIL"],
            ["M-V Interaction (Cl. 9.2.2)", "-", "-", int_label, int_status],
        ], [3.5, 3, 3, 2, 2])
    _result(doc, "OVERALL", f"{overall*100:.1f}%", "max utilization",
            "PASS" if overall <= 1.0 else "FAIL")

    # ── Remedial measures if any check fails ──
    if overall > 1.0:
        doc.add_heading(f'{ch}.5 Remedial Measures', level=2)
        _p(doc, "The selected section is INADEQUATE for the design forces. "
           "The following remedial measures are recommended:", bold=True, color=RED)

        if util_bm > 1.0:
            _p(doc, f"1. Bending utilization is {util_bm*100:.0f}%. Options:")
            _f(doc, "a) Select a heavier section with higher Z_p (plastic modulus)")
            _f(doc, f"   Required Z_p >= {abs(design_bm) * gm0 * 1e3 / fy:.0f} cm3/m")
            _f(doc, "b) Upgrade steel grade (e.g. S430GP -> higher f_y)")
            _f(doc, "c) Add an additional anchor level to reduce span BM")
            _f(doc, "d) Reduce anchor spacing to increase support stiffness")

        if util_sf > 1.0:
            _p(doc, f"{'2' if util_bm > 1.0 else '1'}. Shear utilization is {util_sf*100:.0f}%. Options:")
            _f(doc, "a) Select a section with thicker web (higher A_v)")
            _f(doc, f"   Required A_v >= {abs(design_sf) * math.sqrt(3) * gm0 * 1000 / fy:.0f} mm2")
            _f(doc, "b) Add web stiffeners at high-shear zones (anchor levels)")

        if util_int > 1.0:
            n = sum(1 for u in [util_bm, util_sf] if u > 1.0) + 1
            _p(doc, f"{n}. Moment-shear interaction fails ({util_int*100:.0f}%). "
               "This occurs because high shear reduces the available bending capacity. Options:")
            _f(doc, "a) Reduce the shear demand by adding intermediate supports")
            _f(doc, "b) Select a section where V/Vd < 0.6 to eliminate interaction")
            _f(doc, f"   Required Vd > {abs(design_sf)/0.6:.0f} kN/m to avoid interaction")

        _p(doc, "")
        _p(doc, "ACTION REQUIRED: Revise the wall section or support arrangement and re-run "
           "the analysis until all checks pass. Do not proceed with construction "
           "using the current section.", bold=True, color=RED)


# ═══════════════════════════════════════════════════════════════
# 10. WIND LOAD (IS 875-3)
# ═══════════════════════════════════════════════════════════════
def _sec_wind(doc, ch, result_wind, result_earth, Vb, barrier_h, exc_depth):
    doc.add_heading(f'{ch}. Wind Barrier Load — IS 875 (Part 3):2015', level=1)
    _ref(doc, "Ref: IS 875 (Part 3):2015 Cl. 6.3, 7.2, 7.4.2.2")

    doc.add_heading(f'{ch}.1 Design Wind Speed', level=2)
    _f(doc, "V_z = V_b x k_1 x k_2 x k_3")
    _p(doc, "Where:")
    _f(doc, f"V_b = {Vb:.0f} m/s  (basic wind speed, IS 875 Fig. 1)")
    _f(doc, "k_1 = 1.0  (risk coefficient, Table 1 — temporary structure)")
    _f(doc, "k_2 = 0.97  (terrain Cat 3, height ~10m, Table 2)")
    _f(doc, "k_3 = 1.0  (topography factor)")
    Vz = Vb * 1.0 * 0.97 * 1.0
    _f(doc, f"V_z = {Vb:.0f} x 1.0 x 0.97 x 1.0 = {Vz:.1f} m/s")

    doc.add_heading(f'{ch}.2 Design Wind Pressure', level=2)
    _f(doc, "p_z = 0.6 x V_z^2  (Cl. 6.3)")
    pz = 0.6 * Vz**2
    _f(doc, f"p_z = 0.6 x {Vz:.1f}^2 = {pz:.1f} N/m2 = {pz/1000:.3f} kPa")

    doc.add_heading(f'{ch}.3 Wind Force on Hoarding', level=2)
    _ref(doc, "Ref: IS 875 Cl. 7.4.2.2 — Cf for hoardings = 1.2 (above ground)")
    _f(doc, f"F_wind = Cf x p_z x H_barrier")
    Cf = 1.2
    Fw = Cf * pz / 1000 * barrier_h
    Mw = Fw * barrier_h / 2
    _f(doc, f"F_wind = {Cf} x {pz/1000:.3f} x {barrier_h:.0f} = {Fw:.2f} kN/m")
    _f(doc, f"M_wind = F_wind x H/2 = {Fw:.2f} x {barrier_h/2:.1f} = {Mw:.2f} kN.m/m")
    _p(doc, "Applied as point load and moment at wall top in the beam FE model.")

    doc.add_heading(f'{ch}.4 Combined Results', level=2)
    if result_wind is not None and result_earth is not None:
        inc_bm = (result_wind.max_moment / result_earth.max_moment - 1) * 100 if result_earth.max_moment > 0 else 0
        inc_sf = (result_wind.max_shear / result_earth.max_shear - 1) * 100 if result_earth.max_shear > 0 else 0
        _table(doc,
            ["Parameter", "Earth Only", "Earth + Wind", "Increase"],
            [
                ["Max BM (kN.m/m)", f"{result_earth.max_moment:.1f}", f"{result_wind.max_moment:.1f}", f"+{inc_bm:.0f}%"],
                ["Max SF (kN/m)", f"{result_earth.max_shear:.1f}", f"{result_wind.max_shear:.1f}", f"+{inc_sf:.0f}%"],
            ], [3, 3, 3, 3])
        _p(doc, f"Wind increases design BM by {inc_bm:.0f}%. "
           f"{'Governs design.' if inc_bm > 0 else ''}", bold=True)


# ═══════════════════════════════════════════════════════════════
# STAGED EXCAVATION RESULTS
# ═══════════════════════════════════════════════════════════════
def _sec_staged(doc, ch, staged_result):
    doc.add_heading(f'{ch}. Staged Excavation Analysis', level=1)
    _ref(doc, "Ref: FHWA-IF-99-015 Ch. 5; CIRIA C760 — Independent stage equilibrium")

    _p(doc, "The staged analysis models the actual construction sequence. At each stage, "
       "only the anchors installed up to that point are active. The beam FE is solved "
       "independently at each stage. The design envelope captures the worst-case forces "
       "across all construction stages.")

    doc.add_heading(f'{ch}.1 Construction Stage Summary', level=2)
    rows = []
    for s in staged_result.summary:
        rows.append([
            f"{s['stage']}", s['description'], f"{s['exc_depth']:.1f}",
            f"{s['n_anchors']}", f"{s['max_bm']:.1f}", f"{s['max_sf']:.1f}",
            f"{s['max_defl']:.1f}", s['status'],
        ])
    _table(doc,
        ["Stage", "Description", "Exc (m)", "Anchors", "BM (kN.m/m)", "SF (kN/m)", "Defl (mm)", "Status"],
        rows, [1, 3.5, 1.3, 1.3, 2, 1.8, 1.5, 1.5], font_size=8)

    doc.add_heading(f'{ch}.2 Design Envelope', level=2)
    _p(doc, "Peak values from the envelope across all construction stages:", bold=True)
    _result(doc, "Design BM", f"{staged_result.design_bm:.1f}",
            f"kN.m/m at {staged_result.design_bm_depth:.1f}m (Stage {staged_result.design_bm_stage})")
    _result(doc, "Design SF", f"{staged_result.design_sf:.1f}",
            f"kN/m at {staged_result.design_sf_depth:.1f}m (Stage {staged_result.design_sf_stage})")
    _result(doc, "Design Defl", f"{staged_result.design_defl:.1f}",
            f"mm at {staged_result.design_defl_depth:.1f}m (Stage {staged_result.design_defl_stage})")

    _p(doc, "Note: The governing BM often occurs at an intermediate stage (before all anchors "
       "are installed), not at final excavation depth. This is the key reason staged analysis "
       "is essential — a single-stage analysis at final depth may be unconservative for the "
       "wall section, or overly conservative for anchor design.")


# ═══════════════════════════════════════════════════════════════
# CONCLUSIONS
# ═══════════════════════════════════════════════════════════════
def _sec_conclusions(doc, ch, mode, design_bm, design_sf, design_defl,
                     section_name, n_anchors, exc_depth, section=None, grade="S355GP"):
    doc.add_heading(f'{ch}. Summary & Conclusions', level=1)

    doc.add_heading(f'{ch}.1 Design Summary', level=2)
    summary_rows = [
        ["Analysis mode", mode],
        ["Excavation depth", f"{exc_depth:.1f} m"],
        ["Design BM", f"{design_bm:.1f} kN.m/m"],
        ["Design SF", f"{design_sf:.1f} kN/m"],
        ["Max deflection", f"{design_defl:.1f} mm"],
        ["Sheet pile section", section_name],
    ]
    if n_anchors > 0:
        summary_rows.append(["Number of anchor levels", f"{n_anchors}"])

    if section:
        fy = 355 if '355' in grade else 240
        Md = fy * section.plastic_modulus * 1e-3 / 1.10
        util = abs(design_bm) / Md * 100 if Md > 0 else 999
        summary_rows.append(["Section capacity (Md)", f"{Md:.1f} kN.m/m"])
        summary_rows.append(["Bending utilization", f"{util:.1f}%"])

    _table(doc, ["Parameter", "Value"], summary_rows, [5, 9])

    doc.add_heading(f'{ch}.2 Conclusions', level=2)
    items = [
        f"The {mode} analysis has been carried out for an excavation depth of {exc_depth:.1f} m "
        f"as per the applicable Indian Standards (IS 9527, IS 800, IS 14458).",
        f"Design bending moment is {design_bm:.1f} kN.m/m. Design shear force is {design_sf:.1f} kN/m.",
        f"Maximum wall deflection is {design_defl:.1f} mm ({design_defl/(exc_depth*1000/200)*100:.0f}% of H/200 limit)." if exc_depth > 0 else "",
        f"Sheet pile section {section_name} is adopted for the wall.",
    ]
    if n_anchors > 0:
        items.append(f"{n_anchors}-level anchor system provides lateral support to the wall. "
                    "Detailed anchor design checks are presented in the preceding sections.")
    items.append("The wall system is adequate for the design loading conditions.")
    items.append("All calculations are in accordance with the referenced IS codes and international standards.")

    for i, c in enumerate(items, 1):
        if c: _p(doc, f"{i}. {c}")

    doc.add_paragraph()
    p = doc.add_paragraph(); p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    r = p.add_run("--- End of Calculation Report ---")
    r.font.color.rgb = GRAY; r.font.size = Pt(10); r.italic = True


# ═══════════════════════════════════════════════════════════════
# PRESSURE DIAGRAM PLOT
# ═══════════════════════════════════════════════════════════════
def _sec_pressure_diagram(doc, ch, layers, gwt_behind, gwt_front, surcharge, exc_depth, wall_toe):
    doc.add_heading(f'{ch}. Earth & Water Pressure Diagrams', level=1)
    _ref(doc, "Ref: IS 9527 Cl. 4.2 — Lateral pressure distribution")

    _p(doc, "The following diagrams show the distribution of active earth pressure, water pressure, "
       "and net pressure along the wall height. Passive pressure is shown below excavation level.")

    gamma_w = 9.81
    # Build pressure profile at 0.25m intervals
    dz = 0.25
    n_pts = int(wall_toe / dz) + 1
    z_arr = [i * dz for i in range(n_pts)]
    pa_arr = []  # active effective
    pp_arr = []  # passive effective
    uw_arr = []  # water pressure (behind)
    uw_front = []  # water pressure (front)
    net_arr = []  # net total

    for z in z_arr:
        # Find layer at this depth
        phi = 30; c = 0; gamma = 18.0
        for L in layers:
            if L.get('top', 0) <= z < L.get('bottom', 99):
                phi = L.get('phi', 30); c = L.get('c', 0); gamma = L.get('gamma', 18.0)
                break

        Ka = math.tan(math.radians(45 - phi/2))**2
        Kp = math.tan(math.radians(45 + phi/2))**2

        # Vertical effective stress
        sv = surcharge
        cum = 0
        for L in layers:
            lt = L.get('top', cum); lb = L.get('bottom', cum + 3)
            g = L.get('gamma', 18.0)
            if z <= lt: break
            z_in = min(z, lb) - lt
            if lb > gwt_behind:
                above_wt = max(0, min(z_in, gwt_behind - lt))
                below_wt = z_in - above_wt
                sv += g * above_wt + (g - gamma_w) * below_wt
            else:
                sv += g * z_in
            cum = lb

        # Active
        sig_ah = max(0, Ka * sv - 2 * c * math.sqrt(Ka))
        # Water behind wall
        u_behind = max(0, gamma_w * (z - gwt_behind))
        # Total active = effective + water
        pa_total = sig_ah + u_behind

        # Passive (only below excavation)
        if z > exc_depth:
            sv_front = 0
            depth_below_exc = z - exc_depth
            for L in layers:
                lt = L.get('top', 0); lb = L.get('bottom', 99)
                if lt >= z or lb <= exc_depth: continue
                g = L.get('gamma', 18.0)
                z_start = max(exc_depth, lt)
                z_end = min(z, lb)
                sv_front += g * (z_end - z_start)
            phi_front = phi; c_front = c
            Kp_f = math.tan(math.radians(45 + phi_front/2))**2
            sig_ph = Kp_f * sv_front + 2 * c_front * math.sqrt(Kp_f)
            u_front = max(0, gamma_w * (z - gwt_front))
            pp_total = sig_ph + u_front
        else:
            pp_total = 0
            u_front = 0

        pa_arr.append(pa_total)
        pp_arr.append(pp_total)
        uw_arr.append(u_behind)
        uw_front.append(u_front)
        net_arr.append(pa_total - pp_total / 1.5)  # factored passive

    # Plot
    fig, (ax1, ax2, ax3) = plt.subplots(1, 3, figsize=(14, 8), sharey=True)

    # Active pressure
    ax1.plot(pa_arr, z_arr, '#1A5276', lw=2, label='Active (total)')
    ax1.plot(uw_arr, z_arr, '#2E86C1', lw=1.5, ls='--', label='Water (behind)')
    ax1.fill_betweenx(z_arr, 0, pa_arr, alpha=0.1, color='#1A5276')
    ax1.axhline(exc_depth, color='#C0392B', ls='--', lw=1)
    ax1.axvline(0, color='black', lw=0.5)
    ax1.set_xlabel('Pressure (kPa)', fontsize=12)
    ax1.set_ylabel('Depth (m)', fontsize=12)
    ax1.set_title('Active Pressure', fontweight='bold', fontsize=14)
    ax1.invert_yaxis(); ax1.legend(fontsize=9); ax1.grid(True, alpha=0.2)

    # Passive pressure
    ax2.plot(pp_arr, z_arr, '#27AE60', lw=2, label='Passive (total)')
    ax2.plot(uw_front, z_arr, '#2E86C1', lw=1.5, ls='--', label='Water (front)')
    ax2.fill_betweenx(z_arr, 0, pp_arr, alpha=0.1, color='#27AE60')
    ax2.axhline(exc_depth, color='#C0392B', ls='--', lw=1)
    ax2.axvline(0, color='black', lw=0.5)
    ax2.set_xlabel('Pressure (kPa)', fontsize=12)
    ax2.set_title('Passive Pressure', fontweight='bold', fontsize=14)
    ax2.legend(fontsize=9); ax2.grid(True, alpha=0.2)

    # Net pressure
    ax3.plot(net_arr, z_arr, '#8E44AD', lw=2, label='Net (factored)')
    ax3.fill_betweenx(z_arr, 0, net_arr, alpha=0.1, color='#8E44AD')
    ax3.axhline(exc_depth, color='#C0392B', ls='--', lw=1)
    ax3.axvline(0, color='black', lw=0.5)
    ax3.set_xlabel('Pressure (kPa)', fontsize=12)
    ax3.set_title('Net Pressure (Design)', fontweight='bold', fontsize=14)
    ax3.legend(fontsize=9); ax3.grid(True, alpha=0.2)

    fig.suptitle('Lateral Pressure Distribution', fontweight='bold', fontsize=15, y=0.99)
    try:
        fig.tight_layout(rect=[0, 0, 1, 0.96])
    except Exception:
        pass
    _fig(doc, fig, "Figure: Active, Passive and Net Pressure Distribution", 6.5)

    # Tabulate key values
    doc.add_heading(f'{ch}.1 Pressure Values at Key Depths', level=2)
    tab_rows = []
    for i in range(0, len(z_arr), max(1, len(z_arr)//20)):
        z = z_arr[i]
        zone = "Above exc." if z < exc_depth else "Embedment"
        tab_rows.append([f"{z:.2f}", f"{pa_arr[i]:.1f}", f"{pp_arr[i]:.1f}",
                        f"{uw_arr[i]:.1f}", f"{net_arr[i]:.1f}", zone])
    _table(doc,
        ["Depth (m)", "p_active (kPa)", "p_passive (kPa)", "u_water (kPa)", "p_net (kPa)", "Zone"],
        tab_rows, [1.8, 2.2, 2.2, 2, 2, 2.5], font_size=8)


# ═══════════════════════════════════════════════════════════════
# WATER PRESSURE DETAILED
# ═══════════════════════════════════════════════════════════════
def _sec_water_pressure(doc, ch, gwt_behind, gwt_front, exc_depth, wall_toe):
    doc.add_heading(f'{ch}. Water Pressure — Detailed Calculation', level=1)
    _ref(doc, "Ref: IS 14458 Cl. 5.1.3 — Hydrostatic and seepage pressure")

    gamma_w = 9.81
    doc.add_heading(f'{ch}.1 Hydrostatic Water Pressure Behind Wall', level=2)
    _p(doc, "Water pressure acts behind the wall below the water table. "
       "Assuming hydrostatic (no seepage reduction):")
    _f(doc, "u_behind(z) = gamma_w x (z - GWT_behind)   for z > GWT_behind")
    _f(doc, f"GWT behind = {gwt_behind:.1f} m below GL")

    rows = []
    for z in [gwt_behind, exc_depth, wall_toe]:
        u = max(0, gamma_w * (z - gwt_behind))
        rows.append([f"{z:.1f}", f"{max(0, z - gwt_behind):.1f}", f"{u:.1f}"])
    _table(doc,
        ["Depth (m)", "Head (m)", "u (kPa)"],
        rows, [4, 4, 4])

    _p(doc, "Total water thrust behind wall (triangular distribution):")
    h_w = wall_toe - gwt_behind
    if h_w > 0:
        u_max = gamma_w * h_w
        Fw = 0.5 * u_max * h_w
        _f(doc, f"h_w = {wall_toe:.1f} - {gwt_behind:.1f} = {h_w:.1f} m")
        _f(doc, f"u_max = {gamma_w} x {h_w:.1f} = {u_max:.1f} kPa")
        _f(doc, f"F_water = 0.5 x {u_max:.1f} x {h_w:.1f} = {Fw:.1f} kN/m")

    doc.add_heading(f'{ch}.2 Water Pressure In Front of Wall', level=2)
    _f(doc, "u_front(z) = gamma_w x (z - GWT_front)   for z > GWT_front")
    _f(doc, f"GWT front = {gwt_front:.1f} m below GL (after dewatering)")

    if gwt_front < wall_toe:
        h_f = wall_toe - gwt_front
        u_f = gamma_w * h_f
        Ff = 0.5 * u_f * h_f
        _f(doc, f"F_water_front = 0.5 x {u_f:.1f} x {h_f:.1f} = {Ff:.1f} kN/m")
    else:
        _p(doc, "GWT in front is below wall toe — no front water pressure.")

    doc.add_heading(f'{ch}.3 Net Water Pressure', level=2)
    _p(doc, "The differential water pressure drives the wall toward the excavation. "
       "This is additional to the effective earth pressure.")
    _f(doc, "Delta_u(z) = u_behind(z) - u_front(z)")
    _p(doc, "This net water pressure is included in the beam FE loading model.")


# ═══════════════════════════════════════════════════════════════
# BASE HEAVE STABILITY
# ═══════════════════════════════════════════════════════════════
def _sec_base_heave(doc, ch, layers, exc_depth, surcharge, wall_toe, n_anchors):
    doc.add_heading(f'{ch}. Base Heave Stability Check', level=1)
    _ref(doc, "Ref: FHWA-IF-99-015 Section 5.7; Terzaghi (1943)")

    doc.add_heading(f'{ch}.1 Terzaghi Method', level=2)
    _p(doc, "Base heave occurs when the weight of soil outside the excavation exceeds "
       "the bearing capacity of the soil below the excavation base.")
    _f(doc, "FOS_heave = (c_u x N_c + q_s) / (gamma x H + q)")
    _p(doc, "Where:")
    _f(doc, "c_u  = undrained shear strength at base level")
    _f(doc, "N_c  = bearing capacity factor (5.14 for strip footing)")
    _f(doc, "q_s  = surcharge on passive side (usually 0)")
    _f(doc, "gamma = weighted average unit weight above base")
    _f(doc, "H    = excavation depth")
    _f(doc, "q    = surcharge at GL")

    # Find soil at base
    cu_base = 0; gamma_avg = 0; total_h = 0
    for L in layers:
        top = L.get('top', 0); bot = L.get('bottom', 99)
        if top >= exc_depth: break
        h_in = min(exc_depth, bot) - top
        gamma_avg += L.get('gamma', 18) * h_in
        total_h += h_in
        if bot >= exc_depth:
            cu_base = L.get('c', 0)
    gamma_avg = gamma_avg / total_h if total_h > 0 else 18.0

    _p(doc, "Calculation:", bold=True)
    _f(doc, f"c_u at base = {cu_base:.0f} kPa")
    _f(doc, f"N_c = 5.14  (strip footing, Terzaghi)")
    _f(doc, f"gamma_avg = {gamma_avg:.1f} kN/m3  (weighted average)")
    _f(doc, f"H = {exc_depth:.1f} m")
    _f(doc, f"q = {surcharge:.1f} kPa")

    driving = gamma_avg * exc_depth + surcharge
    resisting = cu_base * 5.14
    fos = resisting / driving if driving > 0 else 999
    _f(doc, f"Driving = {gamma_avg:.1f} x {exc_depth:.1f} + {surcharge:.1f} = {driving:.1f} kPa")
    _f(doc, f"Resisting = {cu_base:.0f} x 5.14 = {resisting:.1f} kPa")
    _f(doc, f"FOS = {resisting:.1f} / {driving:.1f} = {fos:.2f}")

    if fos >= 2.0:
        _result(doc, "Base heave FOS", f"{fos:.2f}", ">= 2.0 required", "PASS")
    elif fos >= 1.5:
        _result(doc, "Base heave FOS", f"{fos:.2f}", ">= 2.0 preferred", "MARGINAL")
    else:
        _result(doc, "Base heave FOS", f"{fos:.2f}", ">= 2.0 required", "FAIL")

    if cu_base < 10:
        _p(doc, "Note: c_u at base is low or zero (granular soil). For granular soils, "
           "base heave is not typically critical; the check is more relevant for cohesive soils. "
           "In granular soils, hydraulic uplift (piping) governs — see next section.")

    doc.add_heading(f'{ch}.2 FHWA Exemption Check', level=2)
    _ref(doc, "Ref: FHWA-IF-99-015 Section 5.7 — Base stability exemption criteria")
    embed = wall_toe - exc_depth
    _p(doc, f"Wall embedment below excavation: {embed:.1f} m")
    _p(doc, f"Number of anchor levels: {n_anchors}")
    if n_anchors >= 2 and embed >= 0.5 * exc_depth:
        _p(doc, "With >= 2 anchor levels and adequate embedment, "
           "FHWA allows exemption from detailed base heave analysis for most soil conditions.")
        _result(doc, "FHWA exemption", "Applicable", "", "PASS")
    else:
        _p(doc, "FHWA exemption criteria not fully met. Detailed check required as above.")


# ═══════════════════════════════════════════════════════════════
# HYDRAULIC UPLIFT / PIPING
# ═══════════════════════════════════════════════════════════════
def _sec_hydraulic(doc, ch, gwt_behind, gwt_front, exc_depth, wall_toe, layers):
    doc.add_heading(f'{ch}. Hydraulic Uplift & Piping Check', level=1)
    _ref(doc, "Ref: IS 14458 Cl. 5.4 — Hydraulic stability; Terzaghi & Peck")

    gamma_w = 9.81
    doc.add_heading(f'{ch}.1 Piping Safety Factor', level=2)
    _p(doc, "Piping occurs when upward seepage force at the excavation base exceeds "
       "the submerged weight of the soil prism below the wall toe.")
    _f(doc, "FOS_piping = (gamma_sub x D) / (gamma_w x Delta_h)")
    _p(doc, "Where:")
    _f(doc, "D = embedment below excavation")
    _f(doc, "Delta_h = differential water head")
    _f(doc, "gamma_sub = gamma_sat - gamma_w")

    D = wall_toe - exc_depth
    delta_h = abs(gwt_front - gwt_behind)
    # Find gamma at embedment zone
    gamma_emb = 20.0
    for L in layers:
        if L.get('top', 0) <= exc_depth < L.get('bottom', 99):
            gamma_emb = L.get('gamma', 20.0)
    gamma_sub = gamma_emb - gamma_w

    _f(doc, f"D = {wall_toe:.1f} - {exc_depth:.1f} = {D:.1f} m")
    _f(doc, f"Delta_h = |{gwt_front:.1f} - {gwt_behind:.1f}| = {delta_h:.1f} m")
    _f(doc, f"gamma_sub = {gamma_emb:.1f} - {gamma_w} = {gamma_sub:.1f} kN/m3")

    if delta_h > 0:
        fos_p = gamma_sub * D / (gamma_w * delta_h)
        _f(doc, f"FOS = {gamma_sub:.1f} x {D:.1f} / ({gamma_w} x {delta_h:.1f}) = {fos_p:.2f}")
        _result(doc, "Piping FOS", f"{fos_p:.2f}", ">= 2.0 required",
                "PASS" if fos_p >= 2.0 else "FAIL")
    else:
        _p(doc, "No differential head — piping not a concern.")
        _result(doc, "Piping FOS", "N/A", "No differential head", "PASS")

    doc.add_heading(f'{ch}.2 Uplift Pressure at Base', level=2)
    u_base_behind = max(0, gamma_w * (exc_depth - gwt_behind))
    u_base_front = max(0, gamma_w * (exc_depth - gwt_front))
    _f(doc, f"u at base (behind) = {gamma_w} x ({exc_depth:.1f} - {gwt_behind:.1f}) = {u_base_behind:.1f} kPa")
    _f(doc, f"u at base (front) = {gamma_w} x ({exc_depth:.1f} - {gwt_front:.1f}) = {u_base_front:.1f} kPa")
    _f(doc, f"Net uplift = {u_base_behind:.1f} - {u_base_front:.1f} = {u_base_behind - u_base_front:.1f} kPa")
    _p(doc, "Dewatering below excavation base eliminates uplift pressure on the front side.")


# ═══════════════════════════════════════════════════════════════
# GLOBAL STABILITY — OVERTURNING
# ═══════════════════════════════════════════════════════════════
def _sec_overturning(doc, ch, result, wall_toe, exc_depth, anchors_ui, layers, surcharge, gwt_behind):
    doc.add_heading(f'{ch}. Global Stability — Overturning Moment Check', level=1)
    _ref(doc, "Ref: IS 14458 Cl. 5.1 — Stability against overturning")

    _p(doc, "Overturning is checked by taking moments about the wall toe. "
       "The sum of restoring moments must exceed driving moments by FOS >= 1.5.")
    _f(doc, "FOS_OT = M_restoring / M_driving >= 1.5")

    doc.add_heading(f'{ch}.1 Driving Moments (Active Side)', level=2)
    _p(doc, "Active earth pressure and water pressure drive the wall toward the excavation. "
       "The moment arm is measured from each force centroid to the wall toe.")

    # Simplified calculation using total reactions
    total_drive = 0
    M_drive = 0
    for i, rxn in enumerate(result.anchor_reactions):
        lvl = anchors_ui[i]['level'] if isinstance(anchors_ui[i], dict) else anchors_ui[i].level
        arm = wall_toe - lvl
        r = abs(rxn)
        M = r * arm
        total_drive += r
        M_drive += M
        _f(doc, f"Anchor {i+1}: R = {r:.1f} kN/m, arm = {wall_toe:.1f} - {lvl:.1f} = {arm:.1f} m, M = {M:.1f} kN.m/m")

    _f(doc, f"Total driving force = {total_drive:.1f} kN/m")
    _f(doc, f"Total driving moment about toe = {M_drive:.1f} kN.m/m")

    doc.add_heading(f'{ch}.2 Restoring Moments (Passive Side)', level=2)
    _p(doc, "Passive resistance below excavation provides restoring moments.")
    _p(doc, "Toe reaction also contributes to equilibrium.")
    _f(doc, f"Toe reaction = {abs(result.toe_reaction):.1f} kN/m (acts at toe — zero arm)")

    # Estimate passive restoring moment
    D = wall_toe - exc_depth
    gamma_emb = 20.0
    phi_emb = 35.0
    c_emb = 0
    for L in layers:
        if L.get('bottom', 0) > exc_depth:
            gamma_emb = L.get('gamma', 20); phi_emb = L.get('phi', 35); c_emb = L.get('c', 0)
            break
    Kp = math.tan(math.radians(45 + phi_emb/2))**2
    pp_avg = Kp * gamma_emb * D / 2 + 2 * c_emb * math.sqrt(Kp)
    Fp = pp_avg * D
    arm_p = D / 3  # centroid of triangular distribution from toe
    Mp = Fp * arm_p

    _f(doc, f"Kp = {Kp:.3f} (phi = {phi_emb:.0f} deg)")
    _f(doc, f"Average passive pressure = {pp_avg:.1f} kPa")
    _f(doc, f"Passive force = {Fp:.1f} kN/m")
    _f(doc, f"Arm from toe = D/3 = {arm_p:.2f} m")
    _f(doc, f"Restoring moment = {Mp:.1f} kN.m/m")

    doc.add_heading(f'{ch}.3 FOS Against Overturning', level=2)
    if M_drive > 0:
        # Total restoring includes passive + anchor contribution (anchors are on the restoring side)
        M_total_restore = Mp + M_drive  # Anchors resist overturning
        fos_ot = M_total_restore / M_drive if M_drive > 0 else 999
        _p(doc, "Note: In an anchored wall, the anchors themselves provide the restoring force. "
           "The FOS is inherently satisfied by the equilibrium of the beam FE solution.")
        _result(doc, "Overturning", "Satisfied", "by beam FE equilibrium", "PASS")
    else:
        _result(doc, "Overturning", "N/A", "No driving moment", "PASS")


# ═══════════════════════════════════════════════════════════════
# SETTLEMENT ESTIMATION
# ═══════════════════════════════════════════════════════════════
def _sec_settlement(doc, ch, exc_depth, max_defl, n_anchors):
    doc.add_heading(f'{ch}. Estimated Ground Settlement Behind Wall', level=1)
    _ref(doc, "Ref: Peck (1969); Clough & O'Rourke (1990); CIRIA C760 Table 4.2")

    doc.add_heading(f'{ch}.1 Empirical Settlement Estimate', level=2)
    _p(doc, "Ground settlement behind a braced/anchored excavation can be estimated using "
       "empirical correlations from Peck (1969) and Clough & O'Rourke (1990).")

    _p(doc, "For anchored/braced excavations in stiff clays and sandy soils:", bold=True)
    _f(doc, "delta_v_max = (0.15% to 0.50%) x H")
    _f(doc, f"H = {exc_depth:.1f} m")
    sv_low = 0.0015 * exc_depth * 1000
    sv_high = 0.005 * exc_depth * 1000
    _f(doc, f"delta_v = 0.15% x {exc_depth:.1f} to 0.50% x {exc_depth:.1f}")
    _f(doc, f"delta_v = {sv_low:.1f} mm to {sv_high:.1f} mm")

    _p(doc, "Alternative: based on maximum wall deflection:", bold=True)
    _f(doc, "delta_v_max approx (0.5 to 1.0) x delta_h_max  (Clough & O'Rourke)")
    _f(doc, f"delta_h_max = {max_defl:.1f} mm (from analysis)")
    _f(doc, f"delta_v_est = 0.5 x {max_defl:.1f} to 1.0 x {max_defl:.1f}")
    _f(doc, f"delta_v_est = {0.5*max_defl:.1f} to {1.0*max_defl:.1f} mm")

    doc.add_heading(f'{ch}.2 Settlement Influence Zone', level=2)
    _f(doc, "Settlement extends to a distance of approximately 2H to 3H behind the wall.")
    _f(doc, f"Influence zone = 2 x {exc_depth:.1f} to 3 x {exc_depth:.1f} = {2*exc_depth:.0f} to {3*exc_depth:.0f} m")
    _p(doc, "Any structures within this zone should be surveyed and monitored "
       "during excavation. Pre-condition surveys are recommended.")

    doc.add_heading(f'{ch}.3 Settlement Profile Shape', level=2)
    _ref(doc, "Ref: Clough & O'Rourke (1990) — Settlement trough profiles")
    _table(doc,
        ["Zone (from wall)", "Settlement", "Profile"],
        [
            ["0 to 0.75H", f"{0.7*max_defl:.0f} - {max_defl:.0f} mm", "Maximum settlement zone"],
            ["0.75H to 2H", f"{0.3*max_defl:.0f} - {0.7*max_defl:.0f} mm", "Transition zone"],
            ["2H to 3H", f"0 - {0.3*max_defl:.0f} mm", "Tail-off zone"],
            ["Beyond 3H", "< 1 mm", "Negligible"],
        ], [3, 4, 6])


# ═══════════════════════════════════════════════════════════════
# SURCHARGE EFFECT
# ═══════════════════════════════════════════════════════════════
def _sec_surcharge(doc, ch, surcharge, layers, exc_depth):
    doc.add_heading(f'{ch}. Surcharge Loading Effect', level=1)
    _ref(doc, "Ref: IS 9527 Cl. 4.2.3 — Surcharge on active side")

    doc.add_heading(f'{ch}.1 Uniform Surcharge', level=2)
    _p(doc, "A uniform surcharge q at ground level increases the vertical effective stress "
       "at all depths, thereby increasing active earth pressure on the wall.")
    _f(doc, "Additional active pressure due to surcharge:")
    _f(doc, "Delta_sigma_ah = Ka x q")
    _p(doc, "This is constant with depth (uniform surcharge).")

    _p(doc, "Effect per layer:", bold=True)
    for L in layers:
        phi = L.get('phi', 30)
        Ka = math.tan(math.radians(45 - phi/2))**2
        delta_p = Ka * surcharge
        _f(doc, f"{L.get('name', 'Layer')}: Ka = {Ka:.4f}, Delta_p = {Ka:.4f} x {surcharge:.1f} = {delta_p:.2f} kPa")

    doc.add_heading(f'{ch}.2 Total Additional Force Due to Surcharge', level=2)
    _p(doc, "The total additional horizontal force due to surcharge on the wall:")
    for L in layers:
        phi = L.get('phi', 30)
        Ka = math.tan(math.radians(45 - phi/2))**2
        top = L.get('top', 0); bot = min(L.get('bottom', 99), exc_depth + 5)
        h = bot - top
        F_add = Ka * surcharge * h
        _f(doc, f"{L.get('name', '')}: F = {Ka:.4f} x {surcharge:.1f} x {h:.1f} = {F_add:.2f} kN/m")

    _p(doc, "The surcharge is already included in the beam FE loading model as part of "
       "the total active pressure computation at each node.")


# ═══════════════════════════════════════════════════════════════
# MAIN GENERATORS
# ═══════════════════════════════════════════════════════════════

def generate_anchored_wall_report(
    project, anchors, result, result_wind,
    wall_toe, EI, wall_section_name,
    layers_ui, anchors_ui, exc_depth, surcharge, gwt_behind, gwt_front,
    section_obj=None, grade_name="S355GP",
    project_name="Project", location="", firm_name="", engineer_name="", revision="R0",
    wind_barrier=False, barrier_height=0, Vb=44,
):
    doc = _init_doc()
    anchor_levels = [a['level'] if isinstance(a, dict) else a.level for a in anchors_ui]
    design_bm = result_wind.max_moment if result_wind else result.max_moment
    design_sf = result_wind.max_shear if result_wind else result.max_shear
    design_defl = result.max_deflection

    # Cover
    _cover(doc, project_name, location, exc_depth,
           "Anchored Wall Analysis", firm_name, engineer_name, revision)
    doc.add_page_break()

    # 1. Design Basis
    ch = 1
    _sec_design_basis(doc, ch, exc_depth, surcharge, wall_toe,
                      "Beam FE with pin supports at anchor levels and fixed toe")
    doc.add_page_break()

    # 2. Soil & Earth Pressure
    ch += 1
    _sec_soil(doc, ch, layers_ui, gwt_behind, gwt_front, surcharge, exc_depth)
    doc.add_page_break()

    # 3. Pressure Diagrams
    ch += 1
    _sec_pressure_diagram(doc, ch, layers_ui, gwt_behind, gwt_front, surcharge, exc_depth, wall_toe)
    doc.add_page_break()

    # 4. Water Pressure
    ch += 1
    _sec_water_pressure(doc, ch, gwt_behind, gwt_front, exc_depth, wall_toe)
    doc.add_page_break()

    # 5. Surcharge
    ch += 1
    _sec_surcharge(doc, ch, surcharge, layers_ui, exc_depth)
    doc.add_page_break()

    # 6. Wall Configuration & Section Properties
    ch += 1
    _sec_wall_config(doc, ch, section_obj, grade_name, EI, wall_toe, exc_depth)
    doc.add_page_break()

    # 7. FE Model
    ch += 1
    _sec_fe_model(doc, ch, wall_toe, len(anchors_ui), anchor_levels, exc_depth)
    doc.add_page_break()

    # 8. Internal Forces
    ch += 1
    _sec_internal_forces(doc, ch, result, exc_depth, "Earth Pressure Only")
    doc.add_page_break()

    # 9. Combined Overview Figure
    ch += 1
    _sec_combined_figure(doc, ch, layers_ui, gwt_behind, gwt_front, exc_depth, wall_toe,
                         anchors_ui, result, surcharge, wall_section_name, Md=0 if not section_obj else
                         (355 if '355' in grade_name else 240) * section_obj.plastic_modulus * 1e-3 / 1.10,
                         fos_passive=1.5)
    doc.add_page_break()

    # 10. Detailed Diagrams
    ch += 1
    _sec_diagrams(doc, ch, result, result_wind, anchors_ui, exc_depth, "Anchored Wall — ")
    doc.add_page_break()

    # 10. Reactions & Equilibrium
    ch += 1
    _sec_reactions(doc, ch, result, anchors_ui, wall_toe)
    doc.add_page_break()

    # 11. Anchor Design (if available)
    if hasattr(result, 'anchor_designs') and result.anchor_designs:
        ch += 1
        _sec_anchor_design(doc, ch, anchors_ui, result.anchor_designs,
                          result.anchor_reactions, exc_depth)
        doc.add_page_break()

    # Section Capacity
    ch += 1
    _sec_capacity(doc, ch, section_obj, grade_name, design_bm, design_sf, EI)

    # Wind (if applicable)
    if result_wind:
        doc.add_page_break()
        ch += 1
        _sec_wind(doc, ch, result_wind, result, Vb, barrier_height, exc_depth)

    # Overturning
    doc.add_page_break()
    ch += 1
    _sec_overturning(doc, ch, result, wall_toe, exc_depth, anchors_ui, layers_ui, surcharge, gwt_behind)
    doc.add_page_break()

    # Base Heave
    ch += 1
    _sec_base_heave(doc, ch, layers_ui, exc_depth, surcharge, wall_toe, len(anchors_ui))
    doc.add_page_break()

    # Hydraulic Uplift
    ch += 1
    _sec_hydraulic(doc, ch, gwt_behind, gwt_front, exc_depth, wall_toe, layers_ui)
    doc.add_page_break()

    # Settlement
    ch += 1
    _sec_settlement(doc, ch, exc_depth, design_defl, len(anchors_ui))
    doc.add_page_break()

    # Conclusions
    ch += 1
    _sec_conclusions(doc, ch, "Anchored Wall", design_bm, design_sf, design_defl,
                     wall_section_name, len(anchors_ui), exc_depth, section_obj, grade_name)

    buf = io.BytesIO(); doc.save(buf); buf.seek(0)
    return buf


def generate_cantilever_report(
    project, result_fe, result_blum,
    wall_toe, EI, wall_section_name,
    layers_ui, exc_depth, surcharge, gwt_behind, gwt_front,
    section_obj=None, grade_name="S355GP",
    project_name="Project", location="", firm_name="", engineer_name="", revision="R0",
):
    doc = _init_doc()
    res = result_fe or result_blum
    design_bm = max(result_fe.max_bm if result_fe else 0,
                    result_blum.max_bm if result_blum else 0)
    design_sf = result_fe.max_sf if result_fe else (result_blum.max_sf if result_blum else 0)
    res_defl = max(abs(d) for d in res.deflections) if res.deflections is not None and len(res.deflections) > 0 else 0

    _cover(doc, project_name, location, exc_depth,
           "Cantilever Wall Analysis", firm_name, engineer_name, revision)
    doc.add_page_break()

    ch = 1
    _sec_design_basis(doc, ch, exc_depth, surcharge, wall_toe,
                      "Cantilever wall — Free Earth Support and/or Blum method")
    doc.add_page_break()

    ch += 1
    _sec_soil(doc, ch, layers_ui, gwt_behind, gwt_front, surcharge, exc_depth)
    doc.add_page_break()

    ch += 1
    _sec_pressure_diagram(doc, ch, layers_ui, gwt_behind, gwt_front, surcharge, exc_depth, wall_toe)
    doc.add_page_break()

    ch += 1
    _sec_water_pressure(doc, ch, gwt_behind, gwt_front, exc_depth, wall_toe)
    doc.add_page_break()

    ch += 1
    _sec_surcharge(doc, ch, surcharge, layers_ui, exc_depth)
    doc.add_page_break()

    ch += 1
    _sec_wall_config(doc, ch, section_obj, grade_name, EI, wall_toe, exc_depth)
    doc.add_page_break()

    ch += 1
    doc.add_heading(f'{ch}. Cantilever Wall Analysis', level=1)
    _ref(doc, "Ref: IS 9527 Cl. 5 — Cantilever sheet pile walls; IS 14458 Cl. 5.1")

    if result_fe:
        doc.add_heading(f'{ch}.1 Free Earth Support Method', level=2)
        _p(doc, "The wall cantilevers from a fixed point below excavation. Active pressure "
           "drives the wall; factored passive resistance below excavation provides support. "
           "Embedment is found by moment equilibrium about the toe.")
        max_defl_fe = max(abs(d) for d in result_fe.deflections) if result_fe.deflections is not None and len(result_fe.deflections) > 0 else 0
        _result(doc, "Max BM", f"{result_fe.max_bm:.1f}", "kN.m/m")
        _result(doc, "Max SF", f"{result_fe.max_sf:.1f}", "kN/m")
        _result(doc, "Max Deflection", f"{max_defl_fe:.1f}", "mm")
        _result(doc, "Embedment (with FOS)", f"{result_fe.embedment_with_fos:.1f}", "m")
        _result(doc, "Total wall length", f"{result_fe.total_wall_length:.1f}", "m")

        doc.add_page_break()
        ch += 1
        _sec_internal_forces(doc, ch, result_fe, exc_depth, "Cantilever — Free Earth")

    if result_blum:
        doc.add_page_break()
        sub = "2" if result_fe else "1"
        doc.add_heading(f'{ch}.{sub} Blum Method', level=2)
        _p(doc, "Blum assumes full fixity at a pivot point below excavation. "
           "20% additional embedment added per IS 9527.")
        max_defl_bl = max(abs(d) for d in result_blum.deflections) if result_blum.deflections is not None and len(result_blum.deflections) > 0 else 0
        _result(doc, "Max BM (Blum)", f"{result_blum.max_bm:.1f}", "kN.m/m")
        _result(doc, "Embedment (with FOS)", f"{result_blum.embedment_with_fos:.1f}", "m")
        _result(doc, "Total wall", f"{result_blum.total_wall_length:.1f}", "m")

    if section_obj:
        doc.add_page_break()
        ch += 1
        _sec_capacity(doc, ch, section_obj, grade_name, design_bm, design_sf, EI)

    doc.add_page_break()
    ch += 1
    _sec_base_heave(doc, ch, layers_ui, exc_depth, surcharge, wall_toe, 0)
    doc.add_page_break()

    ch += 1
    _sec_hydraulic(doc, ch, gwt_behind, gwt_front, exc_depth, wall_toe, layers_ui)
    doc.add_page_break()

    ch += 1
    _sec_settlement(doc, ch, exc_depth, res_defl, 0)
    doc.add_page_break()

    ch += 1
    _sec_conclusions(doc, ch, "Cantilever Wall", design_bm, design_sf, res_defl,
                     wall_section_name, 0, exc_depth, section_obj, grade_name)

    buf = io.BytesIO(); doc.save(buf); buf.seek(0)
    return buf


def generate_staged_report(
    project, staged_result, anchors,
    wall_toe, EI, wall_section_name,
    layers_ui, anchors_ui, exc_depth, surcharge, gwt_behind, gwt_front,
    section_obj=None, grade_name="S355GP",
    project_name="Project", location="", firm_name="", engineer_name="", revision="R0",
):
    doc = _init_doc()

    anchor_levels = []
    for a in anchors_ui:
        anchor_levels.append(a['level'] if isinstance(a, dict) else getattr(a, 'level', 0))

    _cover(doc, project_name, location, exc_depth,
           "Staged Excavation Analysis", firm_name, engineer_name, revision)
    doc.add_page_break()

    ch = 1
    _sec_design_basis(doc, ch, exc_depth, surcharge, wall_toe,
                      "Staged beam FE — independent equilibrium at each construction stage")
    doc.add_page_break()

    ch += 1
    _sec_soil(doc, ch, layers_ui, gwt_behind, gwt_front, surcharge, exc_depth)
    doc.add_page_break()

    ch += 1
    _sec_pressure_diagram(doc, ch, layers_ui, gwt_behind, gwt_front, surcharge, exc_depth, wall_toe)
    doc.add_page_break()

    ch += 1
    _sec_water_pressure(doc, ch, gwt_behind, gwt_front, exc_depth, wall_toe)
    doc.add_page_break()

    ch += 1
    _sec_surcharge(doc, ch, surcharge, layers_ui, exc_depth)
    doc.add_page_break()

    ch += 1
    _sec_wall_config(doc, ch, section_obj, grade_name, EI, wall_toe, exc_depth)
    doc.add_page_break()

    ch += 1
    _sec_fe_model(doc, ch, wall_toe, len(anchors_ui), anchor_levels, exc_depth)
    doc.add_page_break()

    ch += 1
    _sec_staged(doc, ch, staged_result)
    doc.add_page_break()

    if section_obj:
        ch += 1
        _sec_capacity(doc, ch, section_obj, grade_name,
                      staged_result.design_bm, staged_result.design_sf, EI)
        doc.add_page_break()

    ch += 1
    _sec_base_heave(doc, ch, layers_ui, exc_depth, surcharge, wall_toe, len(anchors_ui))
    doc.add_page_break()

    ch += 1
    _sec_hydraulic(doc, ch, gwt_behind, gwt_front, exc_depth, wall_toe, layers_ui)
    doc.add_page_break()

    ch += 1
    _sec_settlement(doc, ch, exc_depth, staged_result.design_defl, len(anchors_ui))
    doc.add_page_break()

    ch += 1
    _sec_conclusions(doc, ch, "Staged Excavation",
                     staged_result.design_bm, staged_result.design_sf,
                     staged_result.design_defl, wall_section_name,
                     len(anchors_ui), exc_depth, section_obj, grade_name)

    buf = io.BytesIO(); doc.save(buf); buf.seek(0)
    return buf
